In [1]:
import pandas as pd

In [2]:
dfactuals = pd.read_excel("Hotel Analytics.xlsx","Actuals")

In [10]:
dfactuals

,Visit ID,Month,Room ID,Room type,Room price,Loyalty status,Actual Days Stay,Concern,Concern description,Revenue room,Revenue Food,Revenue Bevarages,Revenue Total
0,1,1,1,Superior King Room,150,0,3,0,NaN,450,153,88,691
1,2,1,1,Superior King Room,150,0,4,1,Bad smells,600,172,121,893
2,3,1,1,Superior King Room,150,0,4,0,NaN,600,288,52,940
3,4,1,1,Superior King Room,150,1,2,0,NaN,300,153,38,491
4,5,1,1,Superior King Room,150,0,5,0,NaN,750,234,11,995
...,...,...,...,...,...,...,...,...,...,...,...,...,...
13581,13582,12,200,One-Bedroom Suite,900,0,1,0,NaN,900,281,70,1251
13582,13583,12,200,One-Bedroom Suite,900,0,2,0,NaN,1800,476,254,2530
13583,13584,12,200,One-Bedroom Suite,900,0,1,0,NaN,900,336,58,1294
13584,13585,12,200,One-Bedroom Suite,900,0,1,0,NaN,900,224,2,1126
13585,13586,12,200,One-Bedroom Suite,900,0,3,0,NaN,2700,1145,115,3960

In [24]:
dfconcerns = dfactuals[dfactuals["Concern"]==1][["Room type","Month","Concern description"]]

In [25]:
dfconcerns

                   Room type  Month                        Concern description
1         Superior King Room      1                                 Bad smells
5         Superior King Room      1                                 Bad smells
28        Superior King Room      5                          Issues with staff
35        Superior King Room      7                                 Bad smells
37        Superior King Room      7         Doesn’t match the website/brochure
50        Superior King Room     10                                 Bad smells
51        Superior King Room     10                            Noisy neighbors
53        Superior King Room     10                           Low-quality food
63        Superior King Room     12                  Temperature of their room
66        Superior King Room      1                          Issues with staff
83        Superior King Room      3                                 Bad smells
88        Superior King Room      3  Rodents, roaches, & other unwanted guests
93        Superior King Room      4         Doesn’t match the website/brochure
98        Superior King Room      4                               No hot water
102       Superior King Room      5                            Noisy neighbors
109       Superior King Room      6                                Dirty rooms
114       Superior King Room      7  Rodents, roaches, & other unwanted guests
115       Superior King Room      7                           Low-quality food
128       Superior King Room     10                         Faulty electronics
130       Superior King Room     10                            Noisy neighbors
135       Superior King Room     11         Doesn’t match the website/brochure
154       Superior King Room      1                            Noisy neighbors
155       Superior King Room      1                            Noisy neighbors
163       Superior King Room      3                                Dirty rooms
164       Superior King Room      3                          Issues with staff
191       Superior King Room      8                            Noisy neighbors
201       Superior King Room     10                                 Bad smells
203       Superior King Room     10         Doesn’t match the website/brochure
208       Superior King Room     11                         Faulty electronics
225       Superior King Room      1                               No hot water
234       Superior King Room      2                          Issues with staff
235       Superior King Room      2                            Noisy neighbors
239       Superior King Room      3                                 Slow Wi-Fi
243       Superior King Room      3                          Issues with staff
249       Superior King Room      4                           Low-quality food
251       Superior King Room      5                                 Bad smells
253       Superior King Room      5                                 Bad smells
256       Superior King Room      5                  Temperature of their room
257       Superior King Room      5                                 Bad smells
258       Superior King Room      6                            Noisy neighbors
267       Superior King Room      8                                 Bad smells
271       Superior King Room      9                            Noisy neighbors
275       Superior King Room     10                               No hot water
278       Superior King Room     10                            Noisy neighbors
281       Superior King Room     10                         Faulty electronics
285       Superior King Room     11                  Temperature of their room
287       Superior King Room     11                                 Bad smells
296       Superior King Room     12                                 Bad smells
303       Superior King Room      2         Doesn’t match the website/brochure
305       Superior King Room      2                                 Bad smells
319       Superior King Room      4                          Issues with staff
326       Superior King Room      5                               No hot water
331       Superior King Room      6                                 Bad smells
340       Superior King Room      8                                 Slow Wi-Fi
341       Superior King Room      8                                 Bad smells
356       Superior King Room     11                            Noisy neighbors
359       Superior King Room     12                                 Bad smells
361       Superior King Room     12                            Noisy neighbors
370       Superior King Room      2                                Dirty rooms
374       Superior King Room      2                            Noisy neighbors
378       Superior King Room      3                            Noisy neighbors
382       Superior King Room      4                            Noisy neighbors
389       Superior King Room      5                                Dirty rooms
399       Superior King Room      6                                Dirty rooms
408       Superior King Room      8                            Noisy neighbors
410       Superior King Room      8                                 Bad smells
414       Superior King Room     10                          Issues with staff
417       Superior King Room     10                          Issues with staff
418       Superior King Room     10                                 Bad smells
422       Superior King Room     11                                Dirty rooms
424       Superior King Room     11                                Dirty rooms
429       Superior King Room     12                            Noisy neighbors
437       Superior King Room      2                                 Bad smells
440       Superior King Room      2                                 Bad smells
441       Superior King Room      2                            Noisy neighbors
444       Superior King Room      2                                 Bad smells
452       Superior King Room      4         Doesn’t match the website/brochure
454       Superior King Room      4                                Dirty rooms
457       Superior King Room      4                         Faulty electronics
466       Superior King Room      6                                Dirty rooms
473       Superior King Room      8                          Issues with staff
477       Superior King Room      9                           Low-quality food
478       Superior King Room     10                                Dirty rooms
479       Superior King Room     10                                 Bad smells
481       Superior King Room     10                                 Bad smells
483       Superior King Room     10                                 Bad smells
485       Superior King Room     10  Rodents, roaches, & other unwanted guests
501       Superior King Room      1  Rodents, roaches, & other unwanted guests
515       Superior King Room      2                                 Slow Wi-Fi
524       Superior King Room      4         Doesn’t match the website/brochure
528       Superior King Room      4                                 Bad smells
534       Superior King Room      5                            Noisy neighbors
551       Superior King Room      9         Doesn’t match the website/brochure
557       Superior King Room     10                                Dirty rooms
559       Superior King Room     10                         Faulty electronics
562       Superior King Room     11                                Dirty rooms
570       Superior King Room     12                                 Bad smells
575       Superior King Room      1  Rodents, roaches, & other unwanted guests
583       Superior King Room      2                                 Bad smells
590       Superior King Room      3                          Issues with staff
592       Superior King Room      3                                 Slow Wi-Fi
610       Superior King Room      7                            Noisy neighbors
624       Superior King Room     10         Doesn’t match the website/brochure
630       Superior King Room     11                                 Slow Wi-Fi
638       Superior King Room     12                                 Slow Wi-Fi
646       Superior King Room      2                                 Bad smells
650       Superior King Room      2                            Noisy neighbors
651       Superior King Room      3                         Faulty electronics
654       Superior King Room      3                            Noisy neighbors
659       Superior King Room      4                                 Slow Wi-Fi
660       Superior King Room      4                            Noisy neighbors
665       Superior King Room      5                                Dirty rooms
669       Superior King Room      6                  Temperature of their room
676       Superior King Room      8                         Faulty electronics
678       Superior King Room      8                         Faulty electronics
683       Superior King Room      9                          Issues with staff
687       Superior King Room     10                            Noisy neighbors
689       Superior King Room     10                                 Bad smells
690       Superior King Room     10                                 Bad smells
692       Superior King Room     10                          Issues with staff
702       Superior King Room     12                            Noisy neighbors
711       Superior King Room      2                         Faulty electronics
712       Superior King Room      2                            Noisy neighbors
720       Superior King Room      3                               No hot water
723       Superior King Room      3                           Low-quality food
729       Superior King Room      4                            Noisy neighbors
736       Superior King Room      5                            Noisy neighbors
740       Superior King Room      5  Rodents, roaches, & other unwanted guests
742       Superior King Room      5                            Noisy neighbors
761       Superior King Room     10                                 Bad smells
762       Superior King Room     10                                 Bad smells
763       Superior King Room     10                         Faulty electronics
768       Superior King Room     12                            Noisy neighbors
782       Superior King Room      2                            Noisy neighbors
784       Superior King Room      2                                 Bad smells
790       Superior King Room      3  Rodents, roaches, & other unwanted guests
793       Superior King Room      3                  Temperature of their room
796       Superior King Room      4                               No hot water
797       Superior King Room      4  Rodents, roaches, & other unwanted guests
798       Superior King Room      4                               No hot water
801       Superior King Room      5                                Dirty rooms
810       Superior King Room      7                            Noisy neighbors
812       Superior King Room      7                            Noisy neighbors
820       Superior King Room      9                                 Bad smells
823       Superior King Room     10         Doesn’t match the website/brochure
830       Superior King Room     10                          Issues with staff
838       Superior King Room     12                                 Bad smells
842       Superior King Room     12                         Faulty electronics
876       Superior King Room      5                                 Bad smells
886       Superior King Room      7                         Faulty electronics
897       Superior King Room     10                  Temperature of their room
905       Superior King Room     11  Rodents, roaches, & other unwanted guests
906       Superior King Room     11                  Temperature of their room
913       Superior King Room     12                         Faulty electronics
918       Superior King Room      1                                 Bad smells
932       Superior King Room      4  Rodents, roaches, & other unwanted guests
968       Superior King Room     11                            Noisy neighbors
971       Superior King Room     11                  Temperature of their room
972       Superior King Room     12                                Dirty rooms
974       Superior King Room     12                         Faulty electronics
982       Superior King Room      2                                 Bad smells
992       Superior King Room      3                                 Slow Wi-Fi
996       Superior King Room      3                          Issues with staff
1012      Superior King Room      6                               No hot water
1024      Superior King Room      9  Rodents, roaches, & other unwanted guests
1039      Superior King Room     11                               No hot water
1041      Superior King Room     12                               No hot water
1043      Superior King Room     12                         Faulty electronics
1048      Superior King Room      1                                 Bad smells
1074      Superior King Room      5                                 Slow Wi-Fi
1084      Superior King Room      6                            Noisy neighbors
1087      Superior King Room      7                            Noisy neighbors
1090      Superior King Room      8         Doesn’t match the website/brochure
1093      Superior King Room      8                            Noisy neighbors
1098      Superior King Room     10                         Faulty electronics
1102      Superior King Room     10  Rodents, roaches, & other unwanted guests
1107      Superior King Room     11  Rodents, roaches, & other unwanted guests
1112      Superior King Room     12                          Issues with staff
1120      Superior King Room      1                  Temperature of their room
1123      Superior King Room      2                            Noisy neighbors
1126      Superior King Room      2                            Noisy neighbors
1135      Superior King Room      3  Rodents, roaches, & other unwanted guests
1136      Superior King Room      3                         Faulty electronics
1141      Superior King Room      4         Doesn’t match the website/brochure
1142      Superior King Room      4                               No hot water
1149      Superior King Room      6                            Noisy neighbors
1160      Superior King Room      8                                Dirty rooms
1176      Superior King Room     11                                 Slow Wi-Fi
1181      Superior King Room     12                            Noisy neighbors
1182      Superior King Room     12                         Faulty electronics
1190      Superior King Room      2  Rodents, roaches, & other unwanted guests
1196      Superior King Room      2                                Dirty rooms
1201      Superior King Room      3                  Temperature of their room
1205      Superior King Room      4                            Noisy neighbors
1209      Superior King Room      4                          Issues with staff
1212      Superior King Room      5                         Faulty electronics
1213      Superior King Room      5                         Faulty electronics
1217      Superior King Room      6                                 Bad smells
1218      Superior King Room      7                                 Bad smells
1219      Superior King Room      7                               No hot water
1223      Superior King Room      8                            Noisy neighbors
1245      Superior King Room     12                         Faulty electronics
1251      Superior King Room      1                               No hot water
1258      Superior King Room      2                                 Bad smells
1261      Superior King Room      2                           Low-quality food
1264      Superior King Room      3                               No hot water
1269      Superior King Room      3                               No hot water
1278      Superior King Room      5                  Temperature of their room
1294      Superior King Room      9                                 Bad smells
1298      Superior King Room     10         Doesn’t match the website/brochure
1304      Superior King Room     10                                Dirty rooms
1308      Superior King Room     10                            Noisy neighbors
1310      Superior King Room     11                               No hot water
1315      Superior King Room     12                           Low-quality food
1322      Superior King Room      1  Rodents, roaches, & other unwanted guests
1330      Superior King Room      2                         Faulty electronics
1339      Superior King Room      4                                Dirty rooms
1344      Superior King Room      5                               No hot water
1349      Superior King Room      6                            Noisy neighbors
1351      Superior King Room      7         Doesn’t match the website/brochure
1354      Superior King Room      7                            Noisy neighbors
1358      Superior King Room      8  Rodents, roaches, & other unwanted guests
1363      Superior King Room      9                            Noisy neighbors
1365      Superior King Room     10                                 Bad smells
1385      Superior King Room     12                                 Bad smells
1386      Superior King Room     12                                 Bad smells
1391      Superior King Room      1  Rodents, roaches, & other unwanted guests
1392      Superior King Room      2                            Noisy neighbors
1396      Superior King Room      2                                 Bad smells
1397      Superior King Room      2                         Faulty electronics
1410      Superior King Room      4                            Noisy neighbors
1413      Superior King Room      4                         Faulty electronics
1419      Superior King Room      5                               No hot water
1424      Superior King Room      7                          Issues with staff
1427      Superior King Room      8  Rodents, roaches, & other unwanted guests
1430      Superior King Room      8                           Low-quality food
1431      Superior King Room      8                               No hot water
1435      Superior King Room      9                         Faulty electronics
1437      Superior King Room     10                         Faulty electronics
1443      Superior King Room     10                          Issues with staff
1455      Superior King Room      1                                 Bad smells
1466      Superior King Room      2                           Low-quality food
1467      Superior King Room      2                            Noisy neighbors
1469      Superior King Room      2                  Temperature of their room
1475      Superior King Room      3                          Issues with staff
1486      Superior King Room      6                          Issues with staff
1490      Superior King Room      7                            Noisy neighbors
1492      Superior King Room      8         Doesn’t match the website/brochure
1496      Superior King Room      8                            Noisy neighbors
1500      Superior King Room     10                  Temperature of their room
1504      Superior King Room     10         Doesn’t match the website/brochure
1516      Superior King Room     12                            Noisy neighbors

In [28]:
dfconcerns.shape

(2632, 3)

In [29]:
dfconcerns["Concern description"].unique()

array(['Bad smells', 'Issues with staff',
       'Doesn’t match the website/brochure', 'Noisy neighbors',
       'Low-quality food', 'Temperature of their room',
       'Rodents, roaches, & other unwanted guests', 'No hot water',
       'Dirty rooms', 'Faulty electronics', 'Slow Wi-Fi'], dtype=object)

In [30]:
dfconcerns.groupby("Concern description").size()

Concern description
Bad smells                                   283
Dirty rooms                                  125
Doesn’t match the website/brochure           221
Faulty electronics                           278
Issues with staff                            146
Low-quality food                             189
No hot water                                 178
Noisy neighbors                              399
Rodents, roaches, & other unwanted guests    146
Slow Wi-Fi                                   182
Temperature of their room                    485
dtype: int64

In [31]:
pd.set_option('display.max_rows', None)
dfconcerns.groupby(["Room type","Concern description"]).size()

Room type              Concern description
Club Deluxe King Room  Bad smells                                    30
                       Dirty rooms                                   23
                       Doesn’t match the website/brochure            53
                       Faulty electronics                            55
                       Issues with staff                             21
                       Low-quality food                              53
                       No hot water                                  23
                       Noisy neighbors                               41
                       Rodents, roaches, & other unwanted guests     23
                       Slow Wi-Fi                                    27
                       Temperature of their room                     19
Executive Suite        Bad smells                                    29
                       Dirty rooms                                   18
                       Doesn’t match the website/brochure            47
                       Faulty electronics                            44
                       Issues with staff                             23
                       Low-quality food                              21
                       No hot water                                  29
                       Noisy neighbors                               45
                       Rodents, roaches, & other unwanted guests     20
                       Slow Wi-Fi                                    32
                       Temperature of their room                     20
King Suite             Bad smells                                    47
                       Dirty rooms                                   20
                       Doesn’t match the website/brochure            25
                       Faulty electronics                            42
                       Issues with staff                             20
                       Low-quality food                              22
                       No hot water                                  36
                       Noisy neighbors                               93
                       Rodents, roaches, & other unwanted guests     34
                       Slow Wi-Fi                                    43
                       Temperature of their room                    395
One-Bedroom Club Room  Bad smells                                     7
                       Dirty rooms                                    4
                       Doesn’t match the website/brochure            31
                       Faulty electronics                            18
                       Issues with staff                             17
                       Low-quality food                              20
                       No hot water                                  13
                       Noisy neighbors                                4
                       Rodents, roaches, & other unwanted guests      6
                       Slow Wi-Fi                                    15
                       Temperature of their room                      5
One-Bedroom Suite      Bad smells                                     3
                       Dirty rooms                                    4
                       Doesn’t match the website/brochure            20
                       Faulty electronics                            30
                       Issues with staff                             11
                       Low-quality food                              32
                       No hot water                                   5
                       Noisy neighbors                                4
                       Rodents, roaches, & other unwanted guests      4
                       Slow Wi-Fi                                     9
                       Temperature of their room                      5
Superior King Room     Bad smells                                   167
                       Dirty rooms                                   56
                       Doesn’t match the website/brochure            45
                       Faulty electronics                            89
                       Issues with staff                             54
                       Low-quality food                              41
                       No hot water                                  72
                       Noisy neighbors                              212
                       Rodents, roaches, & other unwanted guests     59
                       Slow Wi-Fi                                    56
                       Temperature of their room                     41
dtype: int64

In [40]:
dfcounts = dfconcerns.groupby(["Room type","Month","Concern description"],as_index=False).size()

In [41]:
dfcounts.shape

(612, 4)

In [42]:
dfcounts

,Room type,Month,Concern description,size
0,Club Deluxe King Room,1,Bad smells,1
1,Club Deluxe King Room,1,Dirty rooms,2
2,Club Deluxe King Room,1,Doesn’t match the website/brochure,4
3,Club Deluxe King Room,1,Faulty electronics,5
4,Club Deluxe King Room,1,Low-quality food,13
5,Club Deluxe King Room,1,Noisy neighbors,3
6,Club Deluxe King Room,1,"Rodents, roaches, & other unwanted guests",2
7,Club Deluxe King Room,1,Slow Wi-Fi,2
8,Club Deluxe King Room,1,Temperature of their room,2
9,Club Deluxe King Room,2,Bad smells,2
10,Club Deluxe King Room,2,Doesn’t match the website/brochure,5
11,Club Deluxe King Room,2,Faulty electronics,4
12,Club Deluxe King Room,2,Issues with staff,2
13,Club Deluxe King Room,2,Low-quality food,13
14,Club Deluxe King Room,2,No hot water,4
15,Club Deluxe King Room,2,Noisy neighbors,3
16,Club Deluxe King Room,2,"Rodents, roaches, & other unwanted guests",1
17,Club Deluxe King Room,2,Slow Wi-Fi,3
18,Club Deluxe King Room,2,Temperature of their room,1
19,Club Deluxe King Room,3,Bad smells,4
20,Club Deluxe King Room,3,Dirty rooms,3
21,Club Deluxe King Room,3,Doesn’t match the website/brochure,5
22,Club Deluxe King Room,3,Faulty electronics,9
23,Club Deluxe King Room,3,Issues with staff,2
24,Club Deluxe King Room,3,Low-quality food,12
25,Club Deluxe King Room,3,No hot water,2
26,Club Deluxe King Room,3,Noisy neighbors,4
27,Club Deluxe King Room,3,"Rodents, roaches, & other unwanted guests",3
28,Club Deluxe King Room,3,Slow Wi-Fi,4
29,Club Deluxe King Room,3,Temperature of their room,2
30,Club Deluxe King Room,4,Bad smells,1
31,Club Deluxe King Room,4,Dirty rooms,3
32,Club Deluxe King Room,4,Doesn’t match the website/brochure,5
33,Club Deluxe King Room,4,Faulty electronics,7
34,Club Deluxe King Room,4,Issues with staff,1
35,Club Deluxe King Room,4,Low-quality food,5
36,Club Deluxe King Room,4,Noisy neighbors,3
37,Club Deluxe King Room,4,"Rodents, roaches, & other unwanted guests",3
38,Club Deluxe King Room,4,Temperature of their room,1
39,Club Deluxe King Room,5,Bad smells,2
40,Club Deluxe King Room,5,Dirty rooms,2
41,Club Deluxe King Room,5,Doesn’t match the website/brochure,5
42,Club Deluxe King Room,5,Faulty electronics,4
43,Club Deluxe King Room,5,Issues with staff,3
44,Club Deluxe King Room,5,Low-quality food,2
45,Club Deluxe King Room,5,No hot water,2
46,Club Deluxe King Room,5,Noisy neighbors,4
47,Club Deluxe King Room,5,"Rodents, roaches, & other unwanted guests",1
48,Club Deluxe King Room,5,Slow Wi-Fi,4
49,Club Deluxe King Room,5,Temperature of their room,1
50,Club Deluxe King Room,6,Bad smells,1
51,Club Deluxe King Room,6,Dirty rooms,2
52,Club Deluxe King Room,6,Doesn’t match the website/brochure,2
53,Club Deluxe King Room,6,Faulty electronics,5
54,Club Deluxe King Room,6,Issues with staff,1
55,Club Deluxe King Room,6,Low-quality food,2
56,Club Deluxe King Room,6,No hot water,2
57,Club Deluxe King Room,6,Temperature of their room,2
58,Club Deluxe King Room,7,Bad smells,4
59,Club Deluxe King Room,7,Doesn’t match the website/brochure,7
60,Club Deluxe King Room,7,Faulty electronics,4
61,Club Deluxe King Room,7,Issues with staff,4
62,Club Deluxe King Room,7,No hot water,4
63,Club Deluxe King Room,7,Noisy neighbors,2
64,Club Deluxe King Room,7,"Rodents, roaches, & other unwanted guests",4
65,Club Deluxe King Room,7,Slow Wi-Fi,4
66,Club Deluxe King Room,7,Temperature of their room,3
67,Club Deluxe King Room,8,Bad smells,3
68,Club Deluxe King Room,8,Dirty rooms,1
69,Club Deluxe King Room,8,Doesn’t match the website/brochure,3
70,Club Deluxe King Room,8,Faulty electronics,4
71,Club Deluxe King Room,8,Issues with staff,1
72,Club Deluxe King Room,8,Low-quality food,3
73,Club Deluxe King Room,8,No hot water,4
74,Club Deluxe King Room,8,Noisy neighbors,2
75,Club Deluxe King Room,8,"Rodents, roaches, & other unwanted guests",2
76,Club Deluxe King Room,8,Slow Wi-Fi,2
77,Club Deluxe King Room,9,Bad smells,2
78,Club Deluxe King Room,9,Dirty rooms,4
79,Club Deluxe King Room,9,Doesn’t match the website/brochure,4
80,Club Deluxe King Room,9,Faulty electronics,7
81,Club Deluxe King Room,9,Issues with staff,2
82,Club Deluxe King Room,9,Low-quality food,1
83,Club Deluxe King Room,9,No hot water,3
84,Club Deluxe King Room,9,Noisy neighbors,4
85,Club Deluxe King Room,9,"Rodents, roaches, & other unwanted guests",3
86,Club Deluxe King Room,9,Slow Wi-Fi,1
87,Club Deluxe King Room,9,Temperature of their room,3
88,Club Deluxe King Room,10,Bad smells,6
89,Club Deluxe King Room,10,Dirty rooms,2
90,Club Deluxe King Room,10,Doesn’t match the website/brochure,6
91,Club Deluxe King Room,10,Faulty electronics,3
92,Club Deluxe King Room,10,Issues with staff,2
93,Club Deluxe King Room,10,No hot water,1
94,Club Deluxe King Room,10,Noisy neighbors,5
95,Club Deluxe King Room,10,"Rodents, roaches, & other unwanted guests",1
96,Club Deluxe King Room,10,Slow Wi-Fi,1
97,Club Deluxe King Room,10,Temperature of their room,3
98,Club Deluxe King Room,11,Bad smells,4
99,Club Deluxe King Room,11,Dirty rooms,3
100,Club Deluxe King Room,11,Doesn’t match the website/brochure,2
101,Club Deluxe King Room,11,Faulty electronics,3
102,Club Deluxe King Room,11,Low-quality food,1
103,Club Deluxe King Room,11,No hot water,1
104,Club Deluxe King Room,11,Noisy neighbors,5
105,Club Deluxe King Room,11,"Rodents, roaches, & other unwanted guests",2
106,Club Deluxe King Room,11,Slow Wi-Fi,4
107,Club Deluxe King Room,11,Temperature of their room,1
108,Club Deluxe King Room,12,Dirty rooms,1
109,Club Deluxe King Room,12,Doesn’t match the website/brochure,5
110,Club Deluxe King Room,12,Issues with staff,3
111,Club Deluxe King Room,12,Low-quality food,1
112,Club Deluxe King Room,12,Noisy neighbors,6
113,Club Deluxe King Room,12,"Rodents, roaches, & other unwanted guests",1
114,Club Deluxe King Room,12,Slow Wi-Fi,2
115,Executive Suite,1,Bad smells,6
116,Executive Suite,1,Dirty rooms,3
117,Executive Suite,1,Doesn’t match the website/brochure,6
118,Executive Suite,1,Faulty electronics,6
119,Executive Suite,1,Issues with staff,3
120,Executive Suite,1,Low-quality food,3
121,Executive Suite,1,No hot water,3
122,Executive Suite,1,Noisy neighbors,5
123,Executive Suite,1,"Rodents, roaches, & other unwanted guests",2
124,Executive Suite,1,Slow Wi-Fi,6
125,Executive Suite,1,Temperature of their room,1
126,Executive Suite,2,Bad smells,2
127,Executive Suite,2,Dirty rooms,1
128,Executive Suite,2,Doesn’t match the website/brochure,3
129,Executive Suite,2,Faulty electronics,1
130,Executive Suite,2,Low-quality food,3
131,Executive Suite,2,No hot water,1
132,Executive Suite,2,Noisy neighbors,7
133,Executive Suite,2,"Rodents, roaches, & other unwanted guests",1
134,Executive Suite,2,Slow Wi-Fi,3
135,Executive Suite,2,Temperature of their room,1
136,Executive Suite,3,Bad smells,5
137,Executive Suite,3,Dirty rooms,2
138,Executive Suite,3,Doesn’t match the website/brochure,5
139,Executive Suite,3,Faulty electronics,10
140,Executive Suite,3,No hot water,4
141,Executive Suite,3,Noisy neighbors,3
142,Executive Suite,3,"Rodents, roaches, & other unwanted guests",1
143,Executive Suite,3,Slow Wi-Fi,1
144,Executive Suite,3,Temperature of their room,1
145,Executive Suite,4,Bad smells,4
146,Executive Suite,4,Dirty rooms,2
147,Executive Suite,4,Doesn’t match the website/brochure,6
148,Executive Suite,4,Faulty electronics,3
149,Executive Suite,4,Issues with staff,1
150,Executive Suite,4,Low-quality food,1
151,Executive Suite,4,No hot water,1
152,Executive Suite,4,Noisy neighbors,5
153,Executive Suite,4,"Rodents, roaches, & other unwanted guests",1
154,Executive Suite,4,Slow Wi-Fi,3
155,Executive Suite,4,Temperature of their room,3
156,Executive Suite,5,Bad smells,1
157,Executive Suite,5,Dirty rooms,1
158,Executive Suite,5,Doesn’t match the website/brochure,7
159,Executive Suite,5,Faulty electronics,2
160,Executive Suite,5,Low-quality food,2
161,Executive Suite,5,No hot water,2
162,Executive Suite,5,Noisy neighbors,6
163,Executive Suite,5,"Rodents, roaches, & other unwanted guests",2
164,Executive Suite,5,Slow Wi-Fi,2
165,Executive Suite,5,Temperature of their room,3
166,Executive Suite,6,Dirty rooms,1
167,Executive Suite,6,Doesn’t match the website/brochure,2
168,Executive Suite,6,Faulty electronics,3
169,Executive Suite,6,Issues with staff,1
170,Executive Suite,6,No hot water,1
171,Executive Suite,6,Noisy neighbors,1
172,Executive Suite,6,"Rodents, roaches, & other unwanted guests",1
173,Executive Suite,6,Slow Wi-Fi,3
174,Executive Suite,7,Bad smells,3
175,Executive Suite,7,Doesn’t match the website/brochure,6
176,Executive Suite,7,Faulty electronics,2
177,Executive Suite,7,Issues with staff,4
178,Executive Suite,7,No hot water,2
179,Executive Suite,7,"Rodents, roaches, & other unwanted guests",3
180,Executive Suite,7,Slow Wi-Fi,2
181,Executive Suite,7,Temperature of their room,3
182,Executive Suite,8,Bad smells,2
183,Executive Suite,8,Dirty rooms,1
184,Executive Suite,8,Doesn’t match the website/brochure,3
185,Executive Suite,8,Faulty electronics,5
186,Executive Suite,8,Issues with staff,1
187,Executive Suite,8,Low-quality food,2
188,Executive Suite,8,No hot water,4
189,Executive Suite,8,Noisy neighbors,4
190,Executive Suite,8,"Rodents, roaches, & other unwanted guests",3
191,Executive Suite,8,Slow Wi-Fi,1
192,Executive Suite,8,Temperature of their room,2
193,Executive Suite,9,Bad smells,2
194,Executive Suite,9,Dirty rooms,1
195,Executive Suite,9,Doesn’t match the website/brochure,1
196,Executive Suite,9,Faulty electronics,1
197,Executive Suite,9,Issues with staff,4
198,Executive Suite,9,Low-quality food,1
199,Executive Suite,9,Noisy neighbors,3
200,Executive Suite,9,Slow Wi-Fi,4
201,Executive Suite,9,Temperature of their room,2
202,Executive Suite,10,Bad smells,2
203,Executive Suite,10,Dirty rooms,2
204,Executive Suite,10,Doesn’t match the website/brochure,4
205,Executive Suite,10,Faulty electronics,4
206,Executive Suite,10,Issues with staff,2
207,Executive Suite,10,Low-quality food,4
208,Executive Suite,10,No hot water,6
209,Executive Suite,10,Noisy neighbors,4
210,Executive Suite,10,"Rodents, roaches, & other unwanted guests",3
211,Executive Suite,10,Slow Wi-Fi,3
212,Executive Suite,10,Temperature of their room,2
213,Executive Suite,11,Bad smells,1
214,Executive Suite,11,Dirty rooms,2
215,Executive Suite,11,Doesn’t match the website/brochure,1
216,Executive Suite,11,Faulty electronics,1
217,Executive Suite,11,Issues with staff,3
218,Executive Suite,11,Low-quality food,2
219,Executive Suite,11,No hot water,1
220,Executive Suite,11,Noisy neighbors,5
221,Executive Suite,11,Slow Wi-Fi,3
222,Executive Suite,11,Temperature of their room,1
223,Executive Suite,12,Bad smells,1
224,Executive Suite,12,Dirty rooms,2
225,Executive Suite,12,Doesn’t match the website/brochure,3
226,Executive Suite,12,Faulty electronics,6
227,Executive Suite,12,Issues with staff,4
228,Executive Suite,12,Low-quality food,3
229,Executive Suite,12,No hot water,4
230,Executive Suite,12,Noisy neighbors,2
231,Executive Suite,12,"Rodents, roaches, & other unwanted guests",3
232,Executive Suite,12,Slow Wi-Fi,1
233,Executive Suite,12,Temperature of their room,1
234,King Suite,1,Bad smells,11
235,King Suite,1,Dirty rooms,5
236,King Suite,1,Doesn’t match the website/brochure,5
237,King Suite,1,Faulty electronics,14
238,King Suite,1,Issues with staff,4
239,King Suite,1,Low-quality food,9
240,King Suite,1,No hot water,11
241,King Suite,1,Noisy neighbors,17
242,King Suite,1,"Rodents, roaches, & other unwanted guests",9
243,King Suite,1,Slow Wi-Fi,6
244,King Suite,1,Temperature of their room,4
245,King Suite,2,Bad smells,8
246,King Suite,2,Dirty rooms,6
247,King Suite,2,Doesn’t match the website/brochure,2
248,King Suite,2,Faulty electronics,7
249,King Suite,2,Issues with staff,4
250,King Suite,2,Low-quality food,2
251,King Suite,2,No hot water,9
252,King Suite,2,Noisy neighbors,13
253,King Suite,2,"Rodents, roaches, & other unwanted guests",4
254,King Suite,2,Slow Wi-Fi,5
255,King Suite,2,Temperature of their room,2
256,King Suite,3,Bad smells,2
257,King Suite,3,Doesn’t match the website/brochure,3
258,King Suite,3,Faulty electronics,5
259,King Suite,3,Low-quality food,2
260,King Suite,3,No hot water,3
261,King Suite,3,Noisy neighbors,14
262,King Suite,3,"Rodents, roaches, & other unwanted guests",4
263,King Suite,3,Slow Wi-Fi,5
264,King Suite,3,Temperature of their room,4
265,King Suite,4,Bad smells,3
266,King Suite,4,Dirty rooms,2
267,King Suite,4,Doesn’t match the website/brochure,2
268,King Suite,4,Faulty electronics,3
269,King Suite,4,Issues with staff,3
270,King Suite,4,Low-quality food,1
271,King Suite,4,No hot water,3
272,King Suite,4,Noisy neighbors,8
273,King Suite,4,"Rodents, roaches, & other unwanted guests",1
274,King Suite,4,Temperature of their room,2
275,King Suite,5,Bad smells,5
276,King Suite,5,Dirty rooms,2
277,King Suite,5,Doesn’t match the website/brochure,1
278,King Suite,5,Faulty electronics,1
279,King Suite,5,Issues with staff,1
280,King Suite,5,Low-quality food,1
281,King Suite,5,No hot water,1
282,King Suite,5,Noisy neighbors,3
283,King Suite,5,"Rodents, roaches, & other unwanted guests",1
284,King Suite,5,Slow Wi-Fi,2
285,King Suite,5,Temperature of their room,1
286,King Suite,6,Bad smells,2
287,King Suite,6,Dirty rooms,2
288,King Suite,6,Doesn’t match the website/brochure,1
289,King Suite,6,Noisy neighbors,3
290,King Suite,6,"Rodents, roaches, & other unwanted guests",1
291,King Suite,6,Slow Wi-Fi,1
292,King Suite,6,Temperature of their room,2
293,King Suite,7,Bad smells,5
294,King Suite,7,Doesn’t match the website/brochure,1
295,King Suite,7,Faulty electronics,3
296,King Suite,7,Issues with staff,4
297,King Suite,7,Low-quality food,2
298,King Suite,7,No hot water,2
299,King Suite,7,Noisy neighbors,6
300,King Suite,7,"Rodents, roaches, & other unwanted guests",4
301,King Suite,7,Slow Wi-Fi,1
302,King Suite,7,Temperature of their room,56
303,King Suite,8,Bad smells,2
304,King Suite,8,Dirty rooms,1
305,King Suite,8,Doesn’t match the website/brochure,1
306,King Suite,8,Low-quality food,2
307,King Suite,8,No hot water,2
308,King Suite,8,Noisy neighbors,8
309,King Suite,8,"Rodents, roaches, & other unwanted guests",3
310,King Suite,8,Slow Wi-Fi,3
311,King Suite,8,Temperature of their room,71
312,King Suite,9,Bad smells,5
313,King Suite,9,Doesn’t match the website/brochure,4
314,King Suite,9,Faulty electronics,1
315,King Suite,9,Issues with staff,1
316,King Suite,9,Low-quality food,2
317,King Suite,9,Noisy neighbors,8
318,King Suite,9,"Rodents, roaches, & other unwanted guests",3
319,King Suite,9,Slow Wi-Fi,8
320,King Suite,9,Temperature of their room,97
321,King Suite,10,Dirty rooms,1
322,King Suite,10,Doesn’t match the website/brochure,1
323,King Suite,10,Faulty electronics,2
324,King Suite,10,Issues with staff,1
325,King Suite,10,Low-quality food,1
326,King Suite,10,No hot water,2
327,King Suite,10,Noisy neighbors,3
328,King Suite,10,"Rodents, roaches, & other unwanted guests",1
329,King Suite,10,Slow Wi-Fi,5
330,King Suite,10,Temperature of their room,50
331,King Suite,11,Bad smells,3
332,King Suite,11,Dirty rooms,1
333,King Suite,11,Doesn’t match the website/brochure,2
334,King Suite,11,Faulty electronics,2
335,King Suite,11,No hot water,1
336,King Suite,11,Noisy neighbors,5
337,King Suite,11,Slow Wi-Fi,2
338,King Suite,11,Temperature of their room,52
339,King Suite,12,Bad smells,1
340,King Suite,12,Doesn’t match the website/brochure,2
341,King Suite,12,Faulty electronics,4
342,King Suite,12,Issues with staff,2
343,King Suite,12,No hot water,2
344,King Suite,12,Noisy neighbors,5
345,King Suite,12,"Rodents, roaches, & other unwanted guests",3
346,King Suite,12,Slow Wi-Fi,5
347,King Suite,12,Temperature of their room,54
348,One-Bedroom Club Room,1,Bad smells,1
349,One-Bedroom Club Room,1,Dirty rooms,1
350,One-Bedroom Club Room,1,Doesn’t match the website/brochure,1
351,One-Bedroom Club Room,1,Faulty electronics,2
352,One-Bedroom Club Room,1,Issues with staff,4
353,One-Bedroom Club Room,1,Low-quality food,6
354,One-Bedroom Club Room,1,"Rodents, roaches, & other unwanted guests",2
355,One-Bedroom Club Room,2,Dirty rooms,1
356,One-Bedroom Club Room,2,Doesn’t match the website/brochure,5
357,One-Bedroom Club Room,2,Faulty electronics,1
358,One-Bedroom Club Room,2,Issues with staff,2
359,One-Bedroom Club Room,2,Low-quality food,3
360,One-Bedroom Club Room,2,No hot water,2
361,One-Bedroom Club Room,2,Noisy neighbors,1
362,One-Bedroom Club Room,2,Slow Wi-Fi,1
363,One-Bedroom Club Room,3,Faulty electronics,3
364,One-Bedroom Club Room,3,Issues with staff,2
365,One-Bedroom Club Room,3,Low-quality food,3
366,One-Bedroom Club Room,3,No hot water,2
367,One-Bedroom Club Room,3,Slow Wi-Fi,1
368,One-Bedroom Club Room,4,Bad smells,1
369,One-Bedroom Club Room,4,Doesn’t match the website/brochure,2
370,One-Bedroom Club Room,4,Faulty electronics,3
371,One-Bedroom Club Room,4,Issues with staff,1
372,One-Bedroom Club Room,4,Low-quality food,2
373,One-Bedroom Club Room,4,Noisy neighbors,1
374,One-Bedroom Club Room,4,Temperature of their room,1
375,One-Bedroom Club Room,5,Dirty rooms,1
376,One-Bedroom Club Room,5,Doesn’t match the website/brochure,4
377,One-Bedroom Club Room,5,Faulty electronics,3
378,One-Bedroom Club Room,5,Issues with staff,2
379,One-Bedroom Club Room,5,Low-quality food,3
380,One-Bedroom Club Room,5,No hot water,2
381,One-Bedroom Club Room,5,"Rodents, roaches, & other unwanted guests",1
382,One-Bedroom Club Room,5,Slow Wi-Fi,2
383,One-Bedroom Club Room,6,Doesn’t match the website/brochure,1
384,One-Bedroom Club Room,6,No hot water,2
385,One-Bedroom Club Room,6,"Rodents, roaches, & other unwanted guests",1
386,One-Bedroom Club Room,6,Slow Wi-Fi,1
387,One-Bedroom Club Room,7,Bad smells,3
388,One-Bedroom Club Room,7,Doesn’t match the website/brochure,6
389,One-Bedroom Club Room,7,Faulty electronics,1
390,One-Bedroom Club Room,7,Issues with staff,1
391,One-Bedroom Club Room,7,Low-quality food,1
392,One-Bedroom Club Room,7,No hot water,1
393,One-Bedroom Club Room,7,Slow Wi-Fi,4
394,One-Bedroom Club Room,7,Temperature of their room,1
395,One-Bedroom Club Room,8,Bad smells,1
396,One-Bedroom Club Room,8,Doesn’t match the website/brochure,5
397,One-Bedroom Club Room,8,Faulty electronics,1
398,One-Bedroom Club Room,8,Issues with staff,2
399,One-Bedroom Club Room,8,No hot water,1
400,One-Bedroom Club Room,8,Noisy neighbors,1
401,One-Bedroom Club Room,8,"Rodents, roaches, & other unwanted guests",1
402,One-Bedroom Club Room,8,Slow Wi-Fi,3
403,One-Bedroom Club Room,9,Doesn’t match the website/brochure,1
404,One-Bedroom Club Room,9,Faulty electronics,1
405,One-Bedroom Club Room,9,Issues with staff,1
406,One-Bedroom Club Room,9,Temperature of their room,1
407,One-Bedroom Club Room,10,Doesn’t match the website/brochure,1
408,One-Bedroom Club Room,10,Faulty electronics,1
409,One-Bedroom Club Room,10,Issues with staff,2
410,One-Bedroom Club Room,10,Low-quality food,2
411,One-Bedroom Club Room,10,No hot water,1
412,One-Bedroom Club Room,10,Slow Wi-Fi,2
413,One-Bedroom Club Room,10,Temperature of their room,1
414,One-Bedroom Club Room,11,Dirty rooms,1
415,One-Bedroom Club Room,11,Doesn’t match the website/brochure,1
416,One-Bedroom Club Room,11,Faulty electronics,2
417,One-Bedroom Club Room,11,No hot water,1
418,One-Bedroom Club Room,11,Noisy neighbors,1
419,One-Bedroom Club Room,11,"Rodents, roaches, & other unwanted guests",1
420,One-Bedroom Club Room,11,Slow Wi-Fi,1
421,One-Bedroom Club Room,12,Bad smells,1
422,One-Bedroom Club Room,12,Doesn’t match the website/brochure,4
423,One-Bedroom Club Room,12,No hot water,1
424,One-Bedroom Club Room,12,Temperature of their room,1
425,One-Bedroom Suite,1,Doesn’t match the website/brochure,2
426,One-Bedroom Suite,1,Faulty electronics,1
427,One-Bedroom Suite,1,Low-quality food,6
428,One-Bedroom Suite,2,Doesn’t match the website/brochure,3
429,One-Bedroom Suite,2,Faulty electronics,2
430,One-Bedroom Suite,2,Low-quality food,8
431,One-Bedroom Suite,2,No hot water,1
432,One-Bedroom Suite,3,Bad smells,1
433,One-Bedroom Suite,3,Doesn’t match the website/brochure,1

In [74]:
concerns = pd.DataFrame(list(dfcounts["Concern description"].unique()),columns=["Concern description"])

In [75]:
concerns

                          Concern description
0                                  Bad smells
1                                 Dirty rooms
2          Doesn’t match the website/brochure
3                          Faulty electronics
4                            Low-quality food
5                             Noisy neighbors
6   Rodents, roaches, & other unwanted guests
7                                  Slow Wi-Fi
8                   Temperature of their room
9                           Issues with staff
10                               No hot water

In [76]:
roomtypes = pd.DataFrame(list(dfcounts["Room type"].unique()),columns=["Room type"])

In [77]:
roomtypes

               Room type
0  Club Deluxe King Room
1        Executive Suite
2             King Suite
3  One-Bedroom Club Room
4      One-Bedroom Suite
5     Superior King Room

In [78]:
months = pd.DataFrame(list(dfcounts["Month"].unique()),columns=["Month"])

In [79]:
months

    Month
0       1
1       2
2       3
3       4
4       5
5       6
6       7
7       8
8       9
9      10
10     11
11     12

In [80]:
ts1 = months.merge(concerns,how="cross")

In [81]:
ts2 = roomtypes.merge(ts1,how="cross")

In [82]:
ts2

                 Room type  Month                        Concern description
0    Club Deluxe King Room      1                                 Bad smells
1    Club Deluxe King Room      1                                Dirty rooms
2    Club Deluxe King Room      1         Doesn’t match the website/brochure
3    Club Deluxe King Room      1                         Faulty electronics
4    Club Deluxe King Room      1                           Low-quality food
5    Club Deluxe King Room      1                            Noisy neighbors
6    Club Deluxe King Room      1  Rodents, roaches, & other unwanted guests
7    Club Deluxe King Room      1                                 Slow Wi-Fi
8    Club Deluxe King Room      1                  Temperature of their room
9    Club Deluxe King Room      1                          Issues with staff
10   Club Deluxe King Room      1                               No hot water
11   Club Deluxe King Room      2                                 Bad smells
12   Club Deluxe King Room      2                                Dirty rooms
13   Club Deluxe King Room      2         Doesn’t match the website/brochure
14   Club Deluxe King Room      2                         Faulty electronics
15   Club Deluxe King Room      2                           Low-quality food
16   Club Deluxe King Room      2                            Noisy neighbors
17   Club Deluxe King Room      2  Rodents, roaches, & other unwanted guests
18   Club Deluxe King Room      2                                 Slow Wi-Fi
19   Club Deluxe King Room      2                  Temperature of their room
20   Club Deluxe King Room      2                          Issues with staff
21   Club Deluxe King Room      2                               No hot water
22   Club Deluxe King Room      3                                 Bad smells
23   Club Deluxe King Room      3                                Dirty rooms
24   Club Deluxe King Room      3         Doesn’t match the website/brochure
25   Club Deluxe King Room      3                         Faulty electronics
26   Club Deluxe King Room      3                           Low-quality food
27   Club Deluxe King Room      3                            Noisy neighbors
28   Club Deluxe King Room      3  Rodents, roaches, & other unwanted guests
29   Club Deluxe King Room      3                                 Slow Wi-Fi
30   Club Deluxe King Room      3                  Temperature of their room
31   Club Deluxe King Room      3                          Issues with staff
32   Club Deluxe King Room      3                               No hot water
33   Club Deluxe King Room      4                                 Bad smells
34   Club Deluxe King Room      4                                Dirty rooms
35   Club Deluxe King Room      4         Doesn’t match the website/brochure
36   Club Deluxe King Room      4                         Faulty electronics
37   Club Deluxe King Room      4                           Low-quality food
38   Club Deluxe King Room      4                            Noisy neighbors
39   Club Deluxe King Room      4  Rodents, roaches, & other unwanted guests
40   Club Deluxe King Room      4                                 Slow Wi-Fi
41   Club Deluxe King Room      4                  Temperature of their room
42   Club Deluxe King Room      4                          Issues with staff
43   Club Deluxe King Room      4                               No hot water
44   Club Deluxe King Room      5                                 Bad smells
45   Club Deluxe King Room      5                                Dirty rooms
46   Club Deluxe King Room      5         Doesn’t match the website/brochure
47   Club Deluxe King Room      5                         Faulty electronics
48   Club Deluxe King Room      5                           Low-quality food
49   Club Deluxe King Room      5                            Noisy neighbors
50   Club Deluxe King Room      5  Rodents, roaches, & other unwanted guests
51   Club Deluxe King Room      5                                 Slow Wi-Fi
52   Club Deluxe King Room      5                  Temperature of their room
53   Club Deluxe King Room      5                          Issues with staff
54   Club Deluxe King Room      5                               No hot water
55   Club Deluxe King Room      6                                 Bad smells
56   Club Deluxe King Room      6                                Dirty rooms
57   Club Deluxe King Room      6         Doesn’t match the website/brochure
58   Club Deluxe King Room      6                         Faulty electronics
59   Club Deluxe King Room      6                           Low-quality food
60   Club Deluxe King Room      6                            Noisy neighbors
61   Club Deluxe King Room      6  Rodents, roaches, & other unwanted guests
62   Club Deluxe King Room      6                                 Slow Wi-Fi
63   Club Deluxe King Room      6                  Temperature of their room
64   Club Deluxe King Room      6                          Issues with staff
65   Club Deluxe King Room      6                               No hot water
66   Club Deluxe King Room      7                                 Bad smells
67   Club Deluxe King Room      7                                Dirty rooms
68   Club Deluxe King Room      7         Doesn’t match the website/brochure
69   Club Deluxe King Room      7                         Faulty electronics
70   Club Deluxe King Room      7                           Low-quality food
71   Club Deluxe King Room      7                            Noisy neighbors
72   Club Deluxe King Room      7  Rodents, roaches, & other unwanted guests
73   Club Deluxe King Room      7                                 Slow Wi-Fi
74   Club Deluxe King Room      7                  Temperature of their room
75   Club Deluxe King Room      7                          Issues with staff
76   Club Deluxe King Room      7                               No hot water
77   Club Deluxe King Room      8                                 Bad smells
78   Club Deluxe King Room      8                                Dirty rooms
79   Club Deluxe King Room      8         Doesn’t match the website/brochure
80   Club Deluxe King Room      8                         Faulty electronics
81   Club Deluxe King Room      8                           Low-quality food
82   Club Deluxe King Room      8                            Noisy neighbors
83   Club Deluxe King Room      8  Rodents, roaches, & other unwanted guests
84   Club Deluxe King Room      8                                 Slow Wi-Fi
85   Club Deluxe King Room      8                  Temperature of their room
86   Club Deluxe King Room      8                          Issues with staff
87   Club Deluxe King Room      8                               No hot water
88   Club Deluxe King Room      9                                 Bad smells
89   Club Deluxe King Room      9                                Dirty rooms
90   Club Deluxe King Room      9         Doesn’t match the website/brochure
91   Club Deluxe King Room      9                         Faulty electronics
92   Club Deluxe King Room      9                           Low-quality food
93   Club Deluxe King Room      9                            Noisy neighbors
94   Club Deluxe King Room      9  Rodents, roaches, & other unwanted guests
95   Club Deluxe King Room      9                                 Slow Wi-Fi
96   Club Deluxe King Room      9                  Temperature of their room
97   Club Deluxe King Room      9                          Issues with staff
98   Club Deluxe King Room      9                               No hot water
99   Club Deluxe King Room     10                                 Bad smells
100  Club Deluxe King Room     10                                Dirty rooms
101  Club Deluxe King Room     10         Doesn’t match the website/brochure
102  Club Deluxe King Room     10                         Faulty electronics
103  Club Deluxe King Room     10                           Low-quality food
104  Club Deluxe King Room     10                            Noisy neighbors
105  Club Deluxe King Room     10  Rodents, roaches, & other unwanted guests
106  Club Deluxe King Room     10                                 Slow Wi-Fi
107  Club Deluxe King Room     10                  Temperature of their room
108  Club Deluxe King Room     10                          Issues with staff
109  Club Deluxe King Room     10                               No hot water
110  Club Deluxe King Room     11                                 Bad smells
111  Club Deluxe King Room     11                                Dirty rooms
112  Club Deluxe King Room     11         Doesn’t match the website/brochure
113  Club Deluxe King Room     11                         Faulty electronics
114  Club Deluxe King Room     11                           Low-quality food
115  Club Deluxe King Room     11                            Noisy neighbors
116  Club Deluxe King Room     11  Rodents, roaches, & other unwanted guests
117  Club Deluxe King Room     11                                 Slow Wi-Fi
118  Club Deluxe King Room     11                  Temperature of their room
119  Club Deluxe King Room     11                          Issues with staff
120  Club Deluxe King Room     11                               No hot water
121  Club Deluxe King Room     12                                 Bad smells
122  Club Deluxe King Room     12                                Dirty rooms
123  Club Deluxe King Room     12         Doesn’t match the website/brochure
124  Club Deluxe King Room     12                         Faulty electronics
125  Club Deluxe King Room     12                           Low-quality food
126  Club Deluxe King Room     12                            Noisy neighbors
127  Club Deluxe King Room     12  Rodents, roaches, & other unwanted guests
128  Club Deluxe King Room     12                                 Slow Wi-Fi
129  Club Deluxe King Room     12                  Temperature of their room
130  Club Deluxe King Room     12                          Issues with staff
131  Club Deluxe King Room     12                               No hot water
132        Executive Suite      1                                 Bad smells
133        Executive Suite      1                                Dirty rooms
134        Executive Suite      1         Doesn’t match the website/brochure
135        Executive Suite      1                         Faulty electronics
136        Executive Suite      1                           Low-quality food
137        Executive Suite      1                            Noisy neighbors
138        Executive Suite      1  Rodents, roaches, & other unwanted guests
139        Executive Suite      1                                 Slow Wi-Fi
140        Executive Suite      1                  Temperature of their room
141        Executive Suite      1                          Issues with staff
142        Executive Suite      1                               No hot water
143        Executive Suite      2                                 Bad smells
144        Executive Suite      2                                Dirty rooms
145        Executive Suite      2         Doesn’t match the website/brochure
146        Executive Suite      2                         Faulty electronics
147        Executive Suite      2                           Low-quality food
148        Executive Suite      2                            Noisy neighbors
149        Executive Suite      2  Rodents, roaches, & other unwanted guests
150        Executive Suite      2                                 Slow Wi-Fi
151        Executive Suite      2                  Temperature of their room
152        Executive Suite      2                          Issues with staff
153        Executive Suite      2                               No hot water
154        Executive Suite      3                                 Bad smells
155        Executive Suite      3                                Dirty rooms
156        Executive Suite      3         Doesn’t match the website/brochure
157        Executive Suite      3                         Faulty electronics
158        Executive Suite      3                           Low-quality food
159        Executive Suite      3                            Noisy neighbors
160        Executive Suite      3  Rodents, roaches, & other unwanted guests
161        Executive Suite      3                                 Slow Wi-Fi
162        Executive Suite      3                  Temperature of their room
163        Executive Suite      3                          Issues with staff
164        Executive Suite      3                               No hot water
165        Executive Suite      4                                 Bad smells
166        Executive Suite      4                                Dirty rooms
167        Executive Suite      4         Doesn’t match the website/brochure
168        Executive Suite      4                         Faulty electronics
169        Executive Suite      4                           Low-quality food
170        Executive Suite      4                            Noisy neighbors
171        Executive Suite      4  Rodents, roaches, & other unwanted guests
172        Executive Suite      4                                 Slow Wi-Fi
173        Executive Suite      4                  Temperature of their room
174        Executive Suite      4                          Issues with staff
175        Executive Suite      4                               No hot water
176        Executive Suite      5                                 Bad smells
177        Executive Suite      5                                Dirty rooms
178        Executive Suite      5         Doesn’t match the website/brochure
179        Executive Suite      5                         Faulty electronics
180        Executive Suite      5                           Low-quality food
181        Executive Suite      5                            Noisy neighbors
182        Executive Suite      5  Rodents, roaches, & other unwanted guests
183        Executive Suite      5                                 Slow Wi-Fi
184        Executive Suite      5                  Temperature of their room
185        Executive Suite      5                          Issues with staff
186        Executive Suite      5                               No hot water
187        Executive Suite      6                                 Bad smells
188        Executive Suite      6                                Dirty rooms
189        Executive Suite      6         Doesn’t match the website/brochure
190        Executive Suite      6                         Faulty electronics
191        Executive Suite      6                           Low-quality food
192        Executive Suite      6                            Noisy neighbors
193        Executive Suite      6  Rodents, roaches, & other unwanted guests
194        Executive Suite      6                                 Slow Wi-Fi
195        Executive Suite      6                  Temperature of their room
196        Executive Suite      6                          Issues with staff
197        Executive Suite      6                               No hot water
198        Executive Suite      7                                 Bad smells
199        Executive Suite      7                                Dirty rooms
200        Executive Suite      7         Doesn’t match the website/brochure
201        Executive Suite      7                         Faulty electronics
202        Executive Suite      7                           Low-quality food
203        Executive Suite      7                            Noisy neighbors
204        Executive Suite      7  Rodents, roaches, & other unwanted guests
205        Executive Suite      7                                 Slow Wi-Fi
206        Executive Suite      7                  Temperature of their room
207        Executive Suite      7                          Issues with staff
208        Executive Suite      7                               No hot water
209        Executive Suite      8                                 Bad smells
210        Executive Suite      8                                Dirty rooms
211        Executive Suite      8         Doesn’t match the website/brochure
212        Executive Suite      8                         Faulty electronics
213        Executive Suite      8                           Low-quality food
214        Executive Suite      8                            Noisy neighbors
215        Executive Suite      8  Rodents, roaches, & other unwanted guests
216        Executive Suite      8                                 Slow Wi-Fi
217        Executive Suite      8                  Temperature of their room
218        Executive Suite      8                          Issues with staff
219        Executive Suite      8                               No hot water
220        Executive Suite      9                                 Bad smells
221        Executive Suite      9                                Dirty rooms
222        Executive Suite      9         Doesn’t match the website/brochure
223        Executive Suite      9                         Faulty electronics
224        Executive Suite      9                           Low-quality food
225        Executive Suite      9                            Noisy neighbors
226        Executive Suite      9  Rodents, roaches, & other unwanted guests
227        Executive Suite      9                                 Slow Wi-Fi
228        Executive Suite      9                  Temperature of their room
229        Executive Suite      9                          Issues with staff
230        Executive Suite      9                               No hot water
231        Executive Suite     10                                 Bad smells
232        Executive Suite     10                                Dirty rooms
233        Executive Suite     10         Doesn’t match the website/brochure
234        Executive Suite     10                         Faulty electronics
235        Executive Suite     10                           Low-quality food
236        Executive Suite     10                            Noisy neighbors
237        Executive Suite     10  Rodents, roaches, & other unwanted guests
238        Executive Suite     10                                 Slow Wi-Fi
239        Executive Suite     10                  Temperature of their room
240        Executive Suite     10                          Issues with staff
241        Executive Suite     10                               No hot water
242        Executive Suite     11                                 Bad smells
243        Executive Suite     11                                Dirty rooms
244        Executive Suite     11         Doesn’t match the website/brochure
245        Executive Suite     11                         Faulty electronics
246        Executive Suite     11                           Low-quality food
247        Executive Suite     11                            Noisy neighbors
248        Executive Suite     11  Rodents, roaches, & other unwanted guests
249        Executive Suite     11                                 Slow Wi-Fi
250        Executive Suite     11                  Temperature of their room
251        Executive Suite     11                          Issues with staff
252        Executive Suite     11                               No hot water
253        Executive Suite     12                                 Bad smells
254        Executive Suite     12                                Dirty rooms
255        Executive Suite     12         Doesn’t match the website/brochure
256        Executive Suite     12                         Faulty electronics
257        Executive Suite     12                           Low-quality food

In [83]:
ts2.shape

(792, 3)

In [84]:
ts2["Count"]=0

In [85]:
ts2

,Room type,Month,Concern description,Count
0,Club Deluxe King Room,1,Bad smells,0
1,Club Deluxe King Room,1,Dirty rooms,0
2,Club Deluxe King Room,1,Doesn’t match the website/brochure,0
3,Club Deluxe King Room,1,Faulty electronics,0
4,Club Deluxe King Room,1,Low-quality food,0
5,Club Deluxe King Room,1,Noisy neighbors,0
6,Club Deluxe King Room,1,"Rodents, roaches, & other unwanted guests",0
7,Club Deluxe King Room,1,Slow Wi-Fi,0
8,Club Deluxe King Room,1,Temperature of their room,0
9,Club Deluxe King Room,1,Issues with staff,0
10,Club Deluxe King Room,1,No hot water,0
11,Club Deluxe King Room,2,Bad smells,0
12,Club Deluxe King Room,2,Dirty rooms,0
13,Club Deluxe King Room,2,Doesn’t match the website/brochure,0
14,Club Deluxe King Room,2,Faulty electronics,0
15,Club Deluxe King Room,2,Low-quality food,0
16,Club Deluxe King Room,2,Noisy neighbors,0
17,Club Deluxe King Room,2,"Rodents, roaches, & other unwanted guests",0
18,Club Deluxe King Room,2,Slow Wi-Fi,0
19,Club Deluxe King Room,2,Temperature of their room,0
20,Club Deluxe King Room,2,Issues with staff,0
21,Club Deluxe King Room,2,No hot water,0
22,Club Deluxe King Room,3,Bad smells,0
23,Club Deluxe King Room,3,Dirty rooms,0
24,Club Deluxe King Room,3,Doesn’t match the website/brochure,0
25,Club Deluxe King Room,3,Faulty electronics,0
26,Club Deluxe King Room,3,Low-quality food,0
27,Club Deluxe King Room,3,Noisy neighbors,0
28,Club Deluxe King Room,3,"Rodents, roaches, & other unwanted guests",0
29,Club Deluxe King Room,3,Slow Wi-Fi,0
30,Club Deluxe King Room,3,Temperature of their room,0
31,Club Deluxe King Room,3,Issues with staff,0
32,Club Deluxe King Room,3,No hot water,0
33,Club Deluxe King Room,4,Bad smells,0
34,Club Deluxe King Room,4,Dirty rooms,0
35,Club Deluxe King Room,4,Doesn’t match the website/brochure,0
36,Club Deluxe King Room,4,Faulty electronics,0
37,Club Deluxe King Room,4,Low-quality food,0
38,Club Deluxe King Room,4,Noisy neighbors,0
39,Club Deluxe King Room,4,"Rodents, roaches, & other unwanted guests",0
40,Club Deluxe King Room,4,Slow Wi-Fi,0
41,Club Deluxe King Room,4,Temperature of their room,0
42,Club Deluxe King Room,4,Issues with staff,0
43,Club Deluxe King Room,4,No hot water,0
44,Club Deluxe King Room,5,Bad smells,0
45,Club Deluxe King Room,5,Dirty rooms,0
46,Club Deluxe King Room,5,Doesn’t match the website/brochure,0
47,Club Deluxe King Room,5,Faulty electronics,0
48,Club Deluxe King Room,5,Low-quality food,0
49,Club Deluxe King Room,5,Noisy neighbors,0
50,Club Deluxe King Room,5,"Rodents, roaches, & other unwanted guests",0
51,Club Deluxe King Room,5,Slow Wi-Fi,0
52,Club Deluxe King Room,5,Temperature of their room,0
53,Club Deluxe King Room,5,Issues with staff,0
54,Club Deluxe King Room,5,No hot water,0
55,Club Deluxe King Room,6,Bad smells,0
56,Club Deluxe King Room,6,Dirty rooms,0
57,Club Deluxe King Room,6,Doesn’t match the website/brochure,0
58,Club Deluxe King Room,6,Faulty electronics,0
59,Club Deluxe King Room,6,Low-quality food,0
60,Club Deluxe King Room,6,Noisy neighbors,0
61,Club Deluxe King Room,6,"Rodents, roaches, & other unwanted guests",0
62,Club Deluxe King Room,6,Slow Wi-Fi,0
63,Club Deluxe King Room,6,Temperature of their room,0
64,Club Deluxe King Room,6,Issues with staff,0
65,Club Deluxe King Room,6,No hot water,0
66,Club Deluxe King Room,7,Bad smells,0
67,Club Deluxe King Room,7,Dirty rooms,0
68,Club Deluxe King Room,7,Doesn’t match the website/brochure,0
69,Club Deluxe King Room,7,Faulty electronics,0
70,Club Deluxe King Room,7,Low-quality food,0
71,Club Deluxe King Room,7,Noisy neighbors,0
72,Club Deluxe King Room,7,"Rodents, roaches, & other unwanted guests",0
73,Club Deluxe King Room,7,Slow Wi-Fi,0
74,Club Deluxe King Room,7,Temperature of their room,0
75,Club Deluxe King Room,7,Issues with staff,0
76,Club Deluxe King Room,7,No hot water,0
77,Club Deluxe King Room,8,Bad smells,0
78,Club Deluxe King Room,8,Dirty rooms,0
79,Club Deluxe King Room,8,Doesn’t match the website/brochure,0
80,Club Deluxe King Room,8,Faulty electronics,0
81,Club Deluxe King Room,8,Low-quality food,0
82,Club Deluxe King Room,8,Noisy neighbors,0
83,Club Deluxe King Room,8,"Rodents, roaches, & other unwanted guests",0
84,Club Deluxe King Room,8,Slow Wi-Fi,0
85,Club Deluxe King Room,8,Temperature of their room,0
86,Club Deluxe King Room,8,Issues with staff,0
87,Club Deluxe King Room,8,No hot water,0
88,Club Deluxe King Room,9,Bad smells,0
89,Club Deluxe King Room,9,Dirty rooms,0
90,Club Deluxe King Room,9,Doesn’t match the website/brochure,0
91,Club Deluxe King Room,9,Faulty electronics,0
92,Club Deluxe King Room,9,Low-quality food,0
93,Club Deluxe King Room,9,Noisy neighbors,0
94,Club Deluxe King Room,9,"Rodents, roaches, & other unwanted guests",0
95,Club Deluxe King Room,9,Slow Wi-Fi,0
96,Club Deluxe King Room,9,Temperature of their room,0
97,Club Deluxe King Room,9,Issues with staff,0
98,Club Deluxe King Room,9,No hot water,0
99,Club Deluxe King Room,10,Bad smells,0
100,Club Deluxe King Room,10,Dirty rooms,0
101,Club Deluxe King Room,10,Doesn’t match the website/brochure,0
102,Club Deluxe King Room,10,Faulty electronics,0
103,Club Deluxe King Room,10,Low-quality food,0
104,Club Deluxe King Room,10,Noisy neighbors,0
105,Club Deluxe King Room,10,"Rodents, roaches, & other unwanted guests",0
106,Club Deluxe King Room,10,Slow Wi-Fi,0
107,Club Deluxe King Room,10,Temperature of their room,0
108,Club Deluxe King Room,10,Issues with staff,0
109,Club Deluxe King Room,10,No hot water,0
110,Club Deluxe King Room,11,Bad smells,0
111,Club Deluxe King Room,11,Dirty rooms,0
112,Club Deluxe King Room,11,Doesn’t match the website/brochure,0
113,Club Deluxe King Room,11,Faulty electronics,0
114,Club Deluxe King Room,11,Low-quality food,0
115,Club Deluxe King Room,11,Noisy neighbors,0
116,Club Deluxe King Room,11,"Rodents, roaches, & other unwanted guests",0
117,Club Deluxe King Room,11,Slow Wi-Fi,0
118,Club Deluxe King Room,11,Temperature of their room,0
119,Club Deluxe King Room,11,Issues with staff,0
120,Club Deluxe King Room,11,No hot water,0
121,Club Deluxe King Room,12,Bad smells,0
122,Club Deluxe King Room,12,Dirty rooms,0
123,Club Deluxe King Room,12,Doesn’t match the website/brochure,0
124,Club Deluxe King Room,12,Faulty electronics,0
125,Club Deluxe King Room,12,Low-quality food,0
126,Club Deluxe King Room,12,Noisy neighbors,0
127,Club Deluxe King Room,12,"Rodents, roaches, & other unwanted guests",0
128,Club Deluxe King Room,12,Slow Wi-Fi,0
129,Club Deluxe King Room,12,Temperature of their room,0
130,Club Deluxe King Room,12,Issues with staff,0
131,Club Deluxe King Room,12,No hot water,0
132,Executive Suite,1,Bad smells,0
133,Executive Suite,1,Dirty rooms,0
134,Executive Suite,1,Doesn’t match the website/brochure,0
135,Executive Suite,1,Faulty electronics,0
136,Executive Suite,1,Low-quality food,0
137,Executive Suite,1,Noisy neighbors,0
138,Executive Suite,1,"Rodents, roaches, & other unwanted guests",0
139,Executive Suite,1,Slow Wi-Fi,0
140,Executive Suite,1,Temperature of their room,0
141,Executive Suite,1,Issues with staff,0
142,Executive Suite,1,No hot water,0
143,Executive Suite,2,Bad smells,0
144,Executive Suite,2,Dirty rooms,0
145,Executive Suite,2,Doesn’t match the website/brochure,0
146,Executive Suite,2,Faulty electronics,0
147,Executive Suite,2,Low-quality food,0
148,Executive Suite,2,Noisy neighbors,0
149,Executive Suite,2,"Rodents, roaches, & other unwanted guests",0
150,Executive Suite,2,Slow Wi-Fi,0
151,Executive Suite,2,Temperature of their room,0
152,Executive Suite,2,Issues with staff,0
153,Executive Suite,2,No hot water,0
154,Executive Suite,3,Bad smells,0
155,Executive Suite,3,Dirty rooms,0
156,Executive Suite,3,Doesn’t match the website/brochure,0
157,Executive Suite,3,Faulty electronics,0
158,Executive Suite,3,Low-quality food,0
159,Executive Suite,3,Noisy neighbors,0
160,Executive Suite,3,"Rodents, roaches, & other unwanted guests",0
161,Executive Suite,3,Slow Wi-Fi,0
162,Executive Suite,3,Temperature of their room,0
163,Executive Suite,3,Issues with staff,0
164,Executive Suite,3,No hot water,0
165,Executive Suite,4,Bad smells,0
166,Executive Suite,4,Dirty rooms,0
167,Executive Suite,4,Doesn’t match the website/brochure,0
168,Executive Suite,4,Faulty electronics,0
169,Executive Suite,4,Low-quality food,0
170,Executive Suite,4,Noisy neighbors,0
171,Executive Suite,4,"Rodents, roaches, & other unwanted guests",0
172,Executive Suite,4,Slow Wi-Fi,0
173,Executive Suite,4,Temperature of their room,0
174,Executive Suite,4,Issues with staff,0
175,Executive Suite,4,No hot water,0
176,Executive Suite,5,Bad smells,0
177,Executive Suite,5,Dirty rooms,0
178,Executive Suite,5,Doesn’t match the website/brochure,0
179,Executive Suite,5,Faulty electronics,0
180,Executive Suite,5,Low-quality food,0
181,Executive Suite,5,Noisy neighbors,0
182,Executive Suite,5,"Rodents, roaches, & other unwanted guests",0
183,Executive Suite,5,Slow Wi-Fi,0
184,Executive Suite,5,Temperature of their room,0
185,Executive Suite,5,Issues with staff,0
186,Executive Suite,5,No hot water,0
187,Executive Suite,6,Bad smells,0
188,Executive Suite,6,Dirty rooms,0
189,Executive Suite,6,Doesn’t match the website/brochure,0
190,Executive Suite,6,Faulty electronics,0
191,Executive Suite,6,Low-quality food,0
192,Executive Suite,6,Noisy neighbors,0
193,Executive Suite,6,"Rodents, roaches, & other unwanted guests",0
194,Executive Suite,6,Slow Wi-Fi,0
195,Executive Suite,6,Temperature of their room,0
196,Executive Suite,6,Issues with staff,0
197,Executive Suite,6,No hot water,0
198,Executive Suite,7,Bad smells,0
199,Executive Suite,7,Dirty rooms,0
200,Executive Suite,7,Doesn’t match the website/brochure,0
201,Executive Suite,7,Faulty electronics,0
202,Executive Suite,7,Low-quality food,0
203,Executive Suite,7,Noisy neighbors,0
204,Executive Suite,7,"Rodents, roaches, & other unwanted guests",0
205,Executive Suite,7,Slow Wi-Fi,0
206,Executive Suite,7,Temperature of their room,0
207,Executive Suite,7,Issues with staff,0
208,Executive Suite,7,No hot water,0
209,Executive Suite,8,Bad smells,0
210,Executive Suite,8,Dirty rooms,0
211,Executive Suite,8,Doesn’t match the website/brochure,0
212,Executive Suite,8,Faulty electronics,0
213,Executive Suite,8,Low-quality food,0
214,Executive Suite,8,Noisy neighbors,0
215,Executive Suite,8,"Rodents, roaches, & other unwanted guests",0
216,Executive Suite,8,Slow Wi-Fi,0
217,Executive Suite,8,Temperature of their room,0
218,Executive Suite,8,Issues with staff,0
219,Executive Suite,8,No hot water,0
220,Executive Suite,9,Bad smells,0
221,Executive Suite,9,Dirty rooms,0
222,Executive Suite,9,Doesn’t match the website/brochure,0
223,Executive Suite,9,Faulty electronics,0
224,Executive Suite,9,Low-quality food,0
225,Executive Suite,9,Noisy neighbors,0
226,Executive Suite,9,"Rodents, roaches, & other unwanted guests",0
227,Executive Suite,9,Slow Wi-Fi,0
228,Executive Suite,9,Temperature of their room,0
229,Executive Suite,9,Issues with staff,0
230,Executive Suite,9,No hot water,0
231,Executive Suite,10,Bad smells,0
232,Executive Suite,10,Dirty rooms,0
233,Executive Suite,10,Doesn’t match the website/brochure,0
234,Executive Suite,10,Faulty electronics,0
235,Executive Suite,10,Low-quality food,0
236,Executive Suite,10,Noisy neighbors,0
237,Executive Suite,10,"Rodents, roaches, & other unwanted guests",0
238,Executive Suite,10,Slow Wi-Fi,0
239,Executive Suite,10,Temperature of their room,0
240,Executive Suite,10,Issues with staff,0
241,Executive Suite,10,No hot water,0
242,Executive Suite,11,Bad smells,0
243,Executive Suite,11,Dirty rooms,0
244,Executive Suite,11,Doesn’t match the website/brochure,0
245,Executive Suite,11,Faulty electronics,0
246,Executive Suite,11,Low-quality food,0
247,Executive Suite,11,Noisy neighbors,0
248,Executive Suite,11,"Rodents, roaches, & other unwanted guests",0
249,Executive Suite,11,Slow Wi-Fi,0
250,Executive Suite,11,Temperature of their room,0
251,Executive Suite,11,Issues with staff,0
252,Executive Suite,11,No hot water,0
253,Executive Suite,12,Bad smells,0
254,Executive Suite,12,Dirty rooms,0
255,Executive Suite,12,Doesn’t match the website/brochure,0
256,Executive Suite,12,Faulty electronics,0
257,Executive Suite,12,Low-quality food,0
258,Executive Suite,12,Noisy neighbors,0
259,Executive Suite,12,"Rodents, roaches, & other unwanted guests",0
260,Executive Suite,12,Slow Wi-Fi,0
261,Executive Suite,12,Temperature of their room,0
262,Executive Suite,12,Issues with staff,0
263,Executive Suite,12,No hot water,0
264,King Suite,1,Bad smells,0
265,King Suite,1,Dirty rooms,0
266,King Suite,1,Doesn’t match the website/brochure,0
267,King Suite,1,Faulty electronics,0
268,King Suite,1,Low-quality food,0
269,King Suite,1,Noisy neighbors,0
270,King Suite,1,"Rodents, roaches, & other unwanted guests",0
271,King Suite,1,Slow Wi-Fi,0
272,King Suite,1,Temperature of their room,0
273,King Suite,1,Issues with staff,0
274,King Suite,1,No hot water,0
275,King Suite,2,Bad smells,0
276,King Suite,2,Dirty rooms,0
277,King Suite,2,Doesn’t match the website/brochure,0
278,King Suite,2,Faulty electronics,0
279,King Suite,2,Low-quality food,0
280,King Suite,2,Noisy neighbors,0
281,King Suite,2,"Rodents, roaches, & other unwanted guests",0
282,King Suite,2,Slow Wi-Fi,0
283,King Suite,2,Temperature of their room,0
284,King Suite,2,Issues with staff,0
285,King Suite,2,No hot water,0
286,King Suite,3,Bad smells,0
287,King Suite,3,Dirty rooms,0
288,King Suite,3,Doesn’t match the website/brochure,0
289,King Suite,3,Faulty electronics,0
290,King Suite,3,Low-quality food,0
291,King Suite,3,Noisy neighbors,0
292,King Suite,3,"Rodents, roaches, & other unwanted guests",0
293,King Suite,3,Slow Wi-Fi,0
294,King Suite,3,Temperature of their room,0
295,King Suite,3,Issues with staff,0
296,King Suite,3,No hot water,0
297,King Suite,4,Bad smells,0
298,King Suite,4,Dirty rooms,0
299,King Suite,4,Doesn’t match the website/brochure,0
300,King Suite,4,Faulty electronics,0
301,King Suite,4,Low-quality food,0
302,King Suite,4,Noisy neighbors,0
303,King Suite,4,"Rodents, roaches, & other unwanted guests",0
304,King Suite,4,Slow Wi-Fi,0
305,King Suite,4,Temperature of their room,0
306,King Suite,4,Issues with staff,0
307,King Suite,4,No hot water,0
308,King Suite,5,Bad smells,0
309,King Suite,5,Dirty rooms,0
310,King Suite,5,Doesn’t match the website/brochure,0
311,King Suite,5,Faulty electronics,0
312,King Suite,5,Low-quality food,0
313,King Suite,5,Noisy neighbors,0
314,King Suite,5,"Rodents, roaches, & other unwanted guests",0
315,King Suite,5,Slow Wi-Fi,0
316,King Suite,5,Temperature of their room,0
317,King Suite,5,Issues with staff,0
318,King Suite,5,No hot water,0
319,King Suite,6,Bad smells,0
320,King Suite,6,Dirty rooms,0
321,King Suite,6,Doesn’t match the website/brochure,0
322,King Suite,6,Faulty electronics,0
323,King Suite,6,Low-quality food,0
324,King Suite,6,Noisy neighbors,0
325,King Suite,6,"Rodents, roaches, & other unwanted guests",0
326,King Suite,6,Slow Wi-Fi,0
327,King Suite,6,Temperature of their room,0
328,King Suite,6,Issues with staff,0
329,King Suite,6,No hot water,0
330,King Suite,7,Bad smells,0
331,King Suite,7,Dirty rooms,0
332,King Suite,7,Doesn’t match the website/brochure,0
333,King Suite,7,Faulty electronics,0
334,King Suite,7,Low-quality food,0
335,King Suite,7,Noisy neighbors,0
336,King Suite,7,"Rodents, roaches, & other unwanted guests",0
337,King Suite,7,Slow Wi-Fi,0
338,King Suite,7,Temperature of their room,0
339,King Suite,7,Issues with staff,0
340,King Suite,7,No hot water,0
341,King Suite,8,Bad smells,0
342,King Suite,8,Dirty rooms,0
343,King Suite,8,Doesn’t match the website/brochure,0
344,King Suite,8,Faulty electronics,0
345,King Suite,8,Low-quality food,0
346,King Suite,8,Noisy neighbors,0
347,King Suite,8,"Rodents, roaches, & other unwanted guests",0
348,King Suite,8,Slow Wi-Fi,0
349,King Suite,8,Temperature of their room,0
350,King Suite,8,Issues with staff,0
351,King Suite,8,No hot water,0
352,King Suite,9,Bad smells,0
353,King Suite,9,Dirty rooms,0
354,King Suite,9,Doesn’t match the website/brochure,0
355,King Suite,9,Faulty electronics,0
356,King Suite,9,Low-quality food,0
357,King Suite,9,Noisy neighbors,0
358,King Suite,9,"Rodents, roaches, & other unwanted guests",0
359,King Suite,9,Slow Wi-Fi,0
360,King Suite,9,Temperature of their room,0
361,King Suite,9,Issues with staff,0
362,King Suite,9,No hot water,0
363,King Suite,10,Bad smells,0
364,King Suite,10,Dirty rooms,0
365,King Suite,10,Doesn’t match the website/brochure,0
366,King Suite,10,Faulty electronics,0
367,King Suite,10,Low-quality food,0
368,King Suite,10,Noisy neighbors,0
369,King Suite,10,"Rodents, roaches, & other unwanted guests",0
370,King Suite,10,Slow Wi-Fi,0
371,King Suite,10,Temperature of their room,0
372,King Suite,10,Issues with staff,0
373,King Suite,10,No hot water,0
374,King Suite,11,Bad smells,0
375,King Suite,11,Dirty rooms,0
376,King Suite,11,Doesn’t match the website/brochure,0
377,King Suite,11,Faulty electronics,0
378,King Suite,11,Low-quality food,0
379,King Suite,11,Noisy neighbors,0
380,King Suite,11,"Rodents, roaches, & other unwanted guests",0
381,King Suite,11,Slow Wi-Fi,0
382,King Suite,11,Temperature of their room,0
383,King Suite,11,Issues with staff,0
384,King Suite,11,No hot water,0
385,King Suite,12,Bad smells,0
386,King Suite,12,Dirty rooms,0
387,King Suite,12,Doesn’t match the website/brochure,0
388,King Suite,12,Faulty electronics,0
389,King Suite,12,Low-quality food,0
390,King Suite,12,Noisy neighbors,0
391,King Suite,12,"Rodents, roaches, & other unwanted guests",0
392,King Suite,12,Slow Wi-Fi,0
393,King Suite,12,Temperature of their room,0
394,King Suite,12,Issues with staff,0
395,King Suite,12,No hot water,0
396,One-Bedroom Club Room,1,Bad smells,0
397,One-Bedroom Club Room,1,Dirty rooms,0
398,One-Bedroom Club Room,1,Doesn’t match the website/brochure,0
399,One-Bedroom Club Room,1,Faulty electronics,0
400,One-Bedroom Club Room,1,Low-quality food,0
401,One-Bedroom Club Room,1,Noisy neighbors,0
402,One-Bedroom Club Room,1,"Rodents, roaches, & other unwanted guests",0
403,One-Bedroom Club Room,1,Slow Wi-Fi,0
404,One-Bedroom Club Room,1,Temperature of their room,0
405,One-Bedroom Club Room,1,Issues with staff,0
406,One-Bedroom Club Room,1,No hot water,0
407,One-Bedroom Club Room,2,Bad smells,0
408,One-Bedroom Club Room,2,Dirty rooms,0
409,One-Bedroom Club Room,2,Doesn’t match the website/brochure,0
410,One-Bedroom Club Room,2,Faulty electronics,0
411,One-Bedroom Club Room,2,Low-quality food,0
412,One-Bedroom Club Room,2,Noisy neighbors,0
413,One-Bedroom Club Room,2,"Rodents, roaches, & other unwanted guests",0
414,One-Bedroom Club Room,2,Slow Wi-Fi,0
415,One-Bedroom Club Room,2,Temperature of their room,0
416,One-Bedroom Club Room,2,Issues with staff,0
417,One-Bedroom Club Room,2,No hot water,0
418,One-Bedroom Club Room,3,Bad smells,0
419,One-Bedroom Club Room,3,Dirty rooms,0
420,One-Bedroom Club Room,3,Doesn’t match the website/brochure,0
421,One-Bedroom Club Room,3,Faulty electronics,0
422,One-Bedroom Club Room,3,Low-quality food,0
423,One-Bedroom Club Room,3,Noisy neighbors,0
424,One-Bedroom Club Room,3,"Rodents, roaches, & other unwanted guests",0
425,One-Bedroom Club Room,3,Slow Wi-Fi,0
426,One-Bedroom Club Room,3,Temperature of their room,0
427,One-Bedroom Club Room,3,Issues with staff,0
428,One-Bedroom Club Room,3,No hot water,0
429,One-Bedroom Club Room,4,Bad smells,0
430,One-Bedroom Club Room,4,Dirty rooms,0
431,One-Bedroom Club Room,4,Doesn’t match the website/brochure,0
432,One-Bedroom Club Room,4,Faulty electronics,0
433,One-Bedroom Club Room,4,Low-quality food,0
434,One-Bedroom Club Room,4,Noisy neighbors,0
435,One-Bedroom Club Room,4,"Rodents, roaches, & other unwanted guests",0
436,One-Bedroom Club Room,4,Slow Wi-Fi,0
437,One-Bedroom Club Room,4,Temperature of their room,0
438,One-Bedroom Club Room,4,Issues with staff,0
439,One-Bedroom Club Room,4,No hot water,0
440,One-Bedroom Club Room,5,Bad smells,0
441,One-Bedroom Club Room,5,Dirty rooms,0

In [86]:
dfcounts

,Room type,Month,Concern description,size
0,Club Deluxe King Room,1,Bad smells,1
1,Club Deluxe King Room,1,Dirty rooms,2
2,Club Deluxe King Room,1,Doesn’t match the website/brochure,4
3,Club Deluxe King Room,1,Faulty electronics,5
4,Club Deluxe King Room,1,Low-quality food,13
5,Club Deluxe King Room,1,Noisy neighbors,3
6,Club Deluxe King Room,1,"Rodents, roaches, & other unwanted guests",2
7,Club Deluxe King Room,1,Slow Wi-Fi,2
8,Club Deluxe King Room,1,Temperature of their room,2
9,Club Deluxe King Room,2,Bad smells,2
10,Club Deluxe King Room,2,Doesn’t match the website/brochure,5
11,Club Deluxe King Room,2,Faulty electronics,4
12,Club Deluxe King Room,2,Issues with staff,2
13,Club Deluxe King Room,2,Low-quality food,13
14,Club Deluxe King Room,2,No hot water,4
15,Club Deluxe King Room,2,Noisy neighbors,3
16,Club Deluxe King Room,2,"Rodents, roaches, & other unwanted guests",1
17,Club Deluxe King Room,2,Slow Wi-Fi,3
18,Club Deluxe King Room,2,Temperature of their room,1
19,Club Deluxe King Room,3,Bad smells,4
20,Club Deluxe King Room,3,Dirty rooms,3
21,Club Deluxe King Room,3,Doesn’t match the website/brochure,5
22,Club Deluxe King Room,3,Faulty electronics,9
23,Club Deluxe King Room,3,Issues with staff,2
24,Club Deluxe King Room,3,Low-quality food,12
25,Club Deluxe King Room,3,No hot water,2
26,Club Deluxe King Room,3,Noisy neighbors,4
27,Club Deluxe King Room,3,"Rodents, roaches, & other unwanted guests",3
28,Club Deluxe King Room,3,Slow Wi-Fi,4
29,Club Deluxe King Room,3,Temperature of their room,2
30,Club Deluxe King Room,4,Bad smells,1
31,Club Deluxe King Room,4,Dirty rooms,3
32,Club Deluxe King Room,4,Doesn’t match the website/brochure,5
33,Club Deluxe King Room,4,Faulty electronics,7
34,Club Deluxe King Room,4,Issues with staff,1
35,Club Deluxe King Room,4,Low-quality food,5
36,Club Deluxe King Room,4,Noisy neighbors,3
37,Club Deluxe King Room,4,"Rodents, roaches, & other unwanted guests",3
38,Club Deluxe King Room,4,Temperature of their room,1
39,Club Deluxe King Room,5,Bad smells,2
40,Club Deluxe King Room,5,Dirty rooms,2
41,Club Deluxe King Room,5,Doesn’t match the website/brochure,5
42,Club Deluxe King Room,5,Faulty electronics,4
43,Club Deluxe King Room,5,Issues with staff,3
44,Club Deluxe King Room,5,Low-quality food,2
45,Club Deluxe King Room,5,No hot water,2
46,Club Deluxe King Room,5,Noisy neighbors,4
47,Club Deluxe King Room,5,"Rodents, roaches, & other unwanted guests",1
48,Club Deluxe King Room,5,Slow Wi-Fi,4
49,Club Deluxe King Room,5,Temperature of their room,1
50,Club Deluxe King Room,6,Bad smells,1
51,Club Deluxe King Room,6,Dirty rooms,2
52,Club Deluxe King Room,6,Doesn’t match the website/brochure,2
53,Club Deluxe King Room,6,Faulty electronics,5
54,Club Deluxe King Room,6,Issues with staff,1
55,Club Deluxe King Room,6,Low-quality food,2
56,Club Deluxe King Room,6,No hot water,2
57,Club Deluxe King Room,6,Temperature of their room,2
58,Club Deluxe King Room,7,Bad smells,4
59,Club Deluxe King Room,7,Doesn’t match the website/brochure,7
60,Club Deluxe King Room,7,Faulty electronics,4
61,Club Deluxe King Room,7,Issues with staff,4
62,Club Deluxe King Room,7,No hot water,4
63,Club Deluxe King Room,7,Noisy neighbors,2
64,Club Deluxe King Room,7,"Rodents, roaches, & other unwanted guests",4
65,Club Deluxe King Room,7,Slow Wi-Fi,4
66,Club Deluxe King Room,7,Temperature of their room,3
67,Club Deluxe King Room,8,Bad smells,3
68,Club Deluxe King Room,8,Dirty rooms,1
69,Club Deluxe King Room,8,Doesn’t match the website/brochure,3
70,Club Deluxe King Room,8,Faulty electronics,4
71,Club Deluxe King Room,8,Issues with staff,1
72,Club Deluxe King Room,8,Low-quality food,3
73,Club Deluxe King Room,8,No hot water,4
74,Club Deluxe King Room,8,Noisy neighbors,2
75,Club Deluxe King Room,8,"Rodents, roaches, & other unwanted guests",2
76,Club Deluxe King Room,8,Slow Wi-Fi,2
77,Club Deluxe King Room,9,Bad smells,2
78,Club Deluxe King Room,9,Dirty rooms,4
79,Club Deluxe King Room,9,Doesn’t match the website/brochure,4
80,Club Deluxe King Room,9,Faulty electronics,7
81,Club Deluxe King Room,9,Issues with staff,2
82,Club Deluxe King Room,9,Low-quality food,1
83,Club Deluxe King Room,9,No hot water,3
84,Club Deluxe King Room,9,Noisy neighbors,4
85,Club Deluxe King Room,9,"Rodents, roaches, & other unwanted guests",3
86,Club Deluxe King Room,9,Slow Wi-Fi,1
87,Club Deluxe King Room,9,Temperature of their room,3
88,Club Deluxe King Room,10,Bad smells,6
89,Club Deluxe King Room,10,Dirty rooms,2
90,Club Deluxe King Room,10,Doesn’t match the website/brochure,6
91,Club Deluxe King Room,10,Faulty electronics,3
92,Club Deluxe King Room,10,Issues with staff,2
93,Club Deluxe King Room,10,No hot water,1
94,Club Deluxe King Room,10,Noisy neighbors,5
95,Club Deluxe King Room,10,"Rodents, roaches, & other unwanted guests",1
96,Club Deluxe King Room,10,Slow Wi-Fi,1
97,Club Deluxe King Room,10,Temperature of their room,3
98,Club Deluxe King Room,11,Bad smells,4
99,Club Deluxe King Room,11,Dirty rooms,3
100,Club Deluxe King Room,11,Doesn’t match the website/brochure,2
101,Club Deluxe King Room,11,Faulty electronics,3
102,Club Deluxe King Room,11,Low-quality food,1
103,Club Deluxe King Room,11,No hot water,1
104,Club Deluxe King Room,11,Noisy neighbors,5
105,Club Deluxe King Room,11,"Rodents, roaches, & other unwanted guests",2
106,Club Deluxe King Room,11,Slow Wi-Fi,4
107,Club Deluxe King Room,11,Temperature of their room,1
108,Club Deluxe King Room,12,Dirty rooms,1
109,Club Deluxe King Room,12,Doesn’t match the website/brochure,5
110,Club Deluxe King Room,12,Issues with staff,3
111,Club Deluxe King Room,12,Low-quality food,1
112,Club Deluxe King Room,12,Noisy neighbors,6
113,Club Deluxe King Room,12,"Rodents, roaches, & other unwanted guests",1
114,Club Deluxe King Room,12,Slow Wi-Fi,2
115,Executive Suite,1,Bad smells,6
116,Executive Suite,1,Dirty rooms,3
117,Executive Suite,1,Doesn’t match the website/brochure,6
118,Executive Suite,1,Faulty electronics,6
119,Executive Suite,1,Issues with staff,3
120,Executive Suite,1,Low-quality food,3
121,Executive Suite,1,No hot water,3
122,Executive Suite,1,Noisy neighbors,5
123,Executive Suite,1,"Rodents, roaches, & other unwanted guests",2
124,Executive Suite,1,Slow Wi-Fi,6
125,Executive Suite,1,Temperature of their room,1
126,Executive Suite,2,Bad smells,2
127,Executive Suite,2,Dirty rooms,1
128,Executive Suite,2,Doesn’t match the website/brochure,3
129,Executive Suite,2,Faulty electronics,1
130,Executive Suite,2,Low-quality food,3
131,Executive Suite,2,No hot water,1
132,Executive Suite,2,Noisy neighbors,7
133,Executive Suite,2,"Rodents, roaches, & other unwanted guests",1
134,Executive Suite,2,Slow Wi-Fi,3
135,Executive Suite,2,Temperature of their room,1
136,Executive Suite,3,Bad smells,5
137,Executive Suite,3,Dirty rooms,2
138,Executive Suite,3,Doesn’t match the website/brochure,5
139,Executive Suite,3,Faulty electronics,10
140,Executive Suite,3,No hot water,4
141,Executive Suite,3,Noisy neighbors,3
142,Executive Suite,3,"Rodents, roaches, & other unwanted guests",1
143,Executive Suite,3,Slow Wi-Fi,1
144,Executive Suite,3,Temperature of their room,1
145,Executive Suite,4,Bad smells,4
146,Executive Suite,4,Dirty rooms,2
147,Executive Suite,4,Doesn’t match the website/brochure,6
148,Executive Suite,4,Faulty electronics,3
149,Executive Suite,4,Issues with staff,1
150,Executive Suite,4,Low-quality food,1
151,Executive Suite,4,No hot water,1
152,Executive Suite,4,Noisy neighbors,5
153,Executive Suite,4,"Rodents, roaches, & other unwanted guests",1
154,Executive Suite,4,Slow Wi-Fi,3
155,Executive Suite,4,Temperature of their room,3
156,Executive Suite,5,Bad smells,1
157,Executive Suite,5,Dirty rooms,1
158,Executive Suite,5,Doesn’t match the website/brochure,7
159,Executive Suite,5,Faulty electronics,2
160,Executive Suite,5,Low-quality food,2
161,Executive Suite,5,No hot water,2
162,Executive Suite,5,Noisy neighbors,6
163,Executive Suite,5,"Rodents, roaches, & other unwanted guests",2
164,Executive Suite,5,Slow Wi-Fi,2
165,Executive Suite,5,Temperature of their room,3
166,Executive Suite,6,Dirty rooms,1
167,Executive Suite,6,Doesn’t match the website/brochure,2
168,Executive Suite,6,Faulty electronics,3
169,Executive Suite,6,Issues with staff,1
170,Executive Suite,6,No hot water,1
171,Executive Suite,6,Noisy neighbors,1
172,Executive Suite,6,"Rodents, roaches, & other unwanted guests",1
173,Executive Suite,6,Slow Wi-Fi,3
174,Executive Suite,7,Bad smells,3
175,Executive Suite,7,Doesn’t match the website/brochure,6
176,Executive Suite,7,Faulty electronics,2
177,Executive Suite,7,Issues with staff,4
178,Executive Suite,7,No hot water,2
179,Executive Suite,7,"Rodents, roaches, & other unwanted guests",3
180,Executive Suite,7,Slow Wi-Fi,2
181,Executive Suite,7,Temperature of their room,3
182,Executive Suite,8,Bad smells,2
183,Executive Suite,8,Dirty rooms,1
184,Executive Suite,8,Doesn’t match the website/brochure,3
185,Executive Suite,8,Faulty electronics,5
186,Executive Suite,8,Issues with staff,1
187,Executive Suite,8,Low-quality food,2
188,Executive Suite,8,No hot water,4
189,Executive Suite,8,Noisy neighbors,4
190,Executive Suite,8,"Rodents, roaches, & other unwanted guests",3
191,Executive Suite,8,Slow Wi-Fi,1
192,Executive Suite,8,Temperature of their room,2
193,Executive Suite,9,Bad smells,2
194,Executive Suite,9,Dirty rooms,1
195,Executive Suite,9,Doesn’t match the website/brochure,1
196,Executive Suite,9,Faulty electronics,1
197,Executive Suite,9,Issues with staff,4
198,Executive Suite,9,Low-quality food,1
199,Executive Suite,9,Noisy neighbors,3
200,Executive Suite,9,Slow Wi-Fi,4
201,Executive Suite,9,Temperature of their room,2
202,Executive Suite,10,Bad smells,2
203,Executive Suite,10,Dirty rooms,2
204,Executive Suite,10,Doesn’t match the website/brochure,4
205,Executive Suite,10,Faulty electronics,4
206,Executive Suite,10,Issues with staff,2
207,Executive Suite,10,Low-quality food,4
208,Executive Suite,10,No hot water,6
209,Executive Suite,10,Noisy neighbors,4
210,Executive Suite,10,"Rodents, roaches, & other unwanted guests",3
211,Executive Suite,10,Slow Wi-Fi,3
212,Executive Suite,10,Temperature of their room,2
213,Executive Suite,11,Bad smells,1
214,Executive Suite,11,Dirty rooms,2
215,Executive Suite,11,Doesn’t match the website/brochure,1
216,Executive Suite,11,Faulty electronics,1
217,Executive Suite,11,Issues with staff,3
218,Executive Suite,11,Low-quality food,2
219,Executive Suite,11,No hot water,1
220,Executive Suite,11,Noisy neighbors,5
221,Executive Suite,11,Slow Wi-Fi,3
222,Executive Suite,11,Temperature of their room,1
223,Executive Suite,12,Bad smells,1
224,Executive Suite,12,Dirty rooms,2
225,Executive Suite,12,Doesn’t match the website/brochure,3
226,Executive Suite,12,Faulty electronics,6
227,Executive Suite,12,Issues with staff,4
228,Executive Suite,12,Low-quality food,3
229,Executive Suite,12,No hot water,4
230,Executive Suite,12,Noisy neighbors,2
231,Executive Suite,12,"Rodents, roaches, & other unwanted guests",3
232,Executive Suite,12,Slow Wi-Fi,1
233,Executive Suite,12,Temperature of their room,1
234,King Suite,1,Bad smells,11
235,King Suite,1,Dirty rooms,5
236,King Suite,1,Doesn’t match the website/brochure,5
237,King Suite,1,Faulty electronics,14
238,King Suite,1,Issues with staff,4
239,King Suite,1,Low-quality food,9
240,King Suite,1,No hot water,11
241,King Suite,1,Noisy neighbors,17
242,King Suite,1,"Rodents, roaches, & other unwanted guests",9
243,King Suite,1,Slow Wi-Fi,6
244,King Suite,1,Temperature of their room,4
245,King Suite,2,Bad smells,8
246,King Suite,2,Dirty rooms,6
247,King Suite,2,Doesn’t match the website/brochure,2
248,King Suite,2,Faulty electronics,7
249,King Suite,2,Issues with staff,4
250,King Suite,2,Low-quality food,2
251,King Suite,2,No hot water,9
252,King Suite,2,Noisy neighbors,13
253,King Suite,2,"Rodents, roaches, & other unwanted guests",4
254,King Suite,2,Slow Wi-Fi,5
255,King Suite,2,Temperature of their room,2
256,King Suite,3,Bad smells,2
257,King Suite,3,Doesn’t match the website/brochure,3
258,King Suite,3,Faulty electronics,5
259,King Suite,3,Low-quality food,2
260,King Suite,3,No hot water,3
261,King Suite,3,Noisy neighbors,14
262,King Suite,3,"Rodents, roaches, & other unwanted guests",4
263,King Suite,3,Slow Wi-Fi,5
264,King Suite,3,Temperature of their room,4
265,King Suite,4,Bad smells,3
266,King Suite,4,Dirty rooms,2
267,King Suite,4,Doesn’t match the website/brochure,2
268,King Suite,4,Faulty electronics,3
269,King Suite,4,Issues with staff,3
270,King Suite,4,Low-quality food,1
271,King Suite,4,No hot water,3
272,King Suite,4,Noisy neighbors,8
273,King Suite,4,"Rodents, roaches, & other unwanted guests",1
274,King Suite,4,Temperature of their room,2
275,King Suite,5,Bad smells,5
276,King Suite,5,Dirty rooms,2
277,King Suite,5,Doesn’t match the website/brochure,1
278,King Suite,5,Faulty electronics,1
279,King Suite,5,Issues with staff,1
280,King Suite,5,Low-quality food,1
281,King Suite,5,No hot water,1
282,King Suite,5,Noisy neighbors,3
283,King Suite,5,"Rodents, roaches, & other unwanted guests",1
284,King Suite,5,Slow Wi-Fi,2
285,King Suite,5,Temperature of their room,1
286,King Suite,6,Bad smells,2
287,King Suite,6,Dirty rooms,2
288,King Suite,6,Doesn’t match the website/brochure,1
289,King Suite,6,Noisy neighbors,3
290,King Suite,6,"Rodents, roaches, & other unwanted guests",1
291,King Suite,6,Slow Wi-Fi,1
292,King Suite,6,Temperature of their room,2
293,King Suite,7,Bad smells,5
294,King Suite,7,Doesn’t match the website/brochure,1
295,King Suite,7,Faulty electronics,3
296,King Suite,7,Issues with staff,4
297,King Suite,7,Low-quality food,2
298,King Suite,7,No hot water,2
299,King Suite,7,Noisy neighbors,6
300,King Suite,7,"Rodents, roaches, & other unwanted guests",4
301,King Suite,7,Slow Wi-Fi,1
302,King Suite,7,Temperature of their room,56
303,King Suite,8,Bad smells,2
304,King Suite,8,Dirty rooms,1
305,King Suite,8,Doesn’t match the website/brochure,1
306,King Suite,8,Low-quality food,2
307,King Suite,8,No hot water,2
308,King Suite,8,Noisy neighbors,8
309,King Suite,8,"Rodents, roaches, & other unwanted guests",3
310,King Suite,8,Slow Wi-Fi,3
311,King Suite,8,Temperature of their room,71
312,King Suite,9,Bad smells,5
313,King Suite,9,Doesn’t match the website/brochure,4
314,King Suite,9,Faulty electronics,1
315,King Suite,9,Issues with staff,1
316,King Suite,9,Low-quality food,2
317,King Suite,9,Noisy neighbors,8
318,King Suite,9,"Rodents, roaches, & other unwanted guests",3
319,King Suite,9,Slow Wi-Fi,8
320,King Suite,9,Temperature of their room,97
321,King Suite,10,Dirty rooms,1
322,King Suite,10,Doesn’t match the website/brochure,1
323,King Suite,10,Faulty electronics,2
324,King Suite,10,Issues with staff,1
325,King Suite,10,Low-quality food,1
326,King Suite,10,No hot water,2
327,King Suite,10,Noisy neighbors,3
328,King Suite,10,"Rodents, roaches, & other unwanted guests",1
329,King Suite,10,Slow Wi-Fi,5
330,King Suite,10,Temperature of their room,50
331,King Suite,11,Bad smells,3
332,King Suite,11,Dirty rooms,1
333,King Suite,11,Doesn’t match the website/brochure,2
334,King Suite,11,Faulty electronics,2
335,King Suite,11,No hot water,1
336,King Suite,11,Noisy neighbors,5
337,King Suite,11,Slow Wi-Fi,2
338,King Suite,11,Temperature of their room,52
339,King Suite,12,Bad smells,1
340,King Suite,12,Doesn’t match the website/brochure,2
341,King Suite,12,Faulty electronics,4
342,King Suite,12,Issues with staff,2
343,King Suite,12,No hot water,2
344,King Suite,12,Noisy neighbors,5
345,King Suite,12,"Rodents, roaches, & other unwanted guests",3
346,King Suite,12,Slow Wi-Fi,5
347,King Suite,12,Temperature of their room,54
348,One-Bedroom Club Room,1,Bad smells,1
349,One-Bedroom Club Room,1,Dirty rooms,1
350,One-Bedroom Club Room,1,Doesn’t match the website/brochure,1
351,One-Bedroom Club Room,1,Faulty electronics,2
352,One-Bedroom Club Room,1,Issues with staff,4
353,One-Bedroom Club Room,1,Low-quality food,6
354,One-Bedroom Club Room,1,"Rodents, roaches, & other unwanted guests",2
355,One-Bedroom Club Room,2,Dirty rooms,1
356,One-Bedroom Club Room,2,Doesn’t match the website/brochure,5
357,One-Bedroom Club Room,2,Faulty electronics,1
358,One-Bedroom Club Room,2,Issues with staff,2
359,One-Bedroom Club Room,2,Low-quality food,3
360,One-Bedroom Club Room,2,No hot water,2
361,One-Bedroom Club Room,2,Noisy neighbors,1
362,One-Bedroom Club Room,2,Slow Wi-Fi,1
363,One-Bedroom Club Room,3,Faulty electronics,3
364,One-Bedroom Club Room,3,Issues with staff,2
365,One-Bedroom Club Room,3,Low-quality food,3
366,One-Bedroom Club Room,3,No hot water,2
367,One-Bedroom Club Room,3,Slow Wi-Fi,1
368,One-Bedroom Club Room,4,Bad smells,1
369,One-Bedroom Club Room,4,Doesn’t match the website/brochure,2
370,One-Bedroom Club Room,4,Faulty electronics,3
371,One-Bedroom Club Room,4,Issues with staff,1
372,One-Bedroom Club Room,4,Low-quality food,2
373,One-Bedroom Club Room,4,Noisy neighbors,1
374,One-Bedroom Club Room,4,Temperature of their room,1
375,One-Bedroom Club Room,5,Dirty rooms,1
376,One-Bedroom Club Room,5,Doesn’t match the website/brochure,4
377,One-Bedroom Club Room,5,Faulty electronics,3
378,One-Bedroom Club Room,5,Issues with staff,2
379,One-Bedroom Club Room,5,Low-quality food,3
380,One-Bedroom Club Room,5,No hot water,2
381,One-Bedroom Club Room,5,"Rodents, roaches, & other unwanted guests",1
382,One-Bedroom Club Room,5,Slow Wi-Fi,2
383,One-Bedroom Club Room,6,Doesn’t match the website/brochure,1
384,One-Bedroom Club Room,6,No hot water,2
385,One-Bedroom Club Room,6,"Rodents, roaches, & other unwanted guests",1
386,One-Bedroom Club Room,6,Slow Wi-Fi,1
387,One-Bedroom Club Room,7,Bad smells,3
388,One-Bedroom Club Room,7,Doesn’t match the website/brochure,6
389,One-Bedroom Club Room,7,Faulty electronics,1
390,One-Bedroom Club Room,7,Issues with staff,1
391,One-Bedroom Club Room,7,Low-quality food,1
392,One-Bedroom Club Room,7,No hot water,1
393,One-Bedroom Club Room,7,Slow Wi-Fi,4
394,One-Bedroom Club Room,7,Temperature of their room,1
395,One-Bedroom Club Room,8,Bad smells,1
396,One-Bedroom Club Room,8,Doesn’t match the website/brochure,5
397,One-Bedroom Club Room,8,Faulty electronics,1
398,One-Bedroom Club Room,8,Issues with staff,2
399,One-Bedroom Club Room,8,No hot water,1
400,One-Bedroom Club Room,8,Noisy neighbors,1
401,One-Bedroom Club Room,8,"Rodents, roaches, & other unwanted guests",1
402,One-Bedroom Club Room,8,Slow Wi-Fi,3
403,One-Bedroom Club Room,9,Doesn’t match the website/brochure,1
404,One-Bedroom Club Room,9,Faulty electronics,1
405,One-Bedroom Club Room,9,Issues with staff,1
406,One-Bedroom Club Room,9,Temperature of their room,1
407,One-Bedroom Club Room,10,Doesn’t match the website/brochure,1
408,One-Bedroom Club Room,10,Faulty electronics,1
409,One-Bedroom Club Room,10,Issues with staff,2
410,One-Bedroom Club Room,10,Low-quality food,2
411,One-Bedroom Club Room,10,No hot water,1
412,One-Bedroom Club Room,10,Slow Wi-Fi,2
413,One-Bedroom Club Room,10,Temperature of their room,1
414,One-Bedroom Club Room,11,Dirty rooms,1
415,One-Bedroom Club Room,11,Doesn’t match the website/brochure,1
416,One-Bedroom Club Room,11,Faulty electronics,2
417,One-Bedroom Club Room,11,No hot water,1
418,One-Bedroom Club Room,11,Noisy neighbors,1
419,One-Bedroom Club Room,11,"Rodents, roaches, & other unwanted guests",1
420,One-Bedroom Club Room,11,Slow Wi-Fi,1
421,One-Bedroom Club Room,12,Bad smells,1
422,One-Bedroom Club Room,12,Doesn’t match the website/brochure,4
423,One-Bedroom Club Room,12,No hot water,1
424,One-Bedroom Club Room,12,Temperature of their room,1
425,One-Bedroom Suite,1,Doesn’t match the website/brochure,2
426,One-Bedroom Suite,1,Faulty electronics,1
427,One-Bedroom Suite,1,Low-quality food,6
428,One-Bedroom Suite,2,Doesn’t match the website/brochure,3
429,One-Bedroom Suite,2,Faulty electronics,2
430,One-Bedroom Suite,2,Low-quality food,8
431,One-Bedroom Suite,2,No hot water,1
432,One-Bedroom Suite,3,Bad smells,1
433,One-Bedroom Suite,3,Doesn’t match the website/brochure,1

In [94]:
ts = ts2.merge(dfcounts,how="left",on=["Room type","Month","Concern description"])

In [95]:
ts.shape

(792, 5)

In [96]:
ts

,Room type,Month,Concern description,Count,size
0,Club Deluxe King Room,1,Bad smells,0,1.0
1,Club Deluxe King Room,1,Dirty rooms,0,2.0
2,Club Deluxe King Room,1,Doesn’t match the website/brochure,0,4.0
3,Club Deluxe King Room,1,Faulty electronics,0,5.0
4,Club Deluxe King Room,1,Low-quality food,0,13.0
5,Club Deluxe King Room,1,Noisy neighbors,0,3.0
6,Club Deluxe King Room,1,"Rodents, roaches, & other unwanted guests",0,2.0
7,Club Deluxe King Room,1,Slow Wi-Fi,0,2.0
8,Club Deluxe King Room,1,Temperature of their room,0,2.0
9,Club Deluxe King Room,1,Issues with staff,0,NaN
10,Club Deluxe King Room,1,No hot water,0,NaN
11,Club Deluxe King Room,2,Bad smells,0,2.0
12,Club Deluxe King Room,2,Dirty rooms,0,NaN
13,Club Deluxe King Room,2,Doesn’t match the website/brochure,0,5.0
14,Club Deluxe King Room,2,Faulty electronics,0,4.0
15,Club Deluxe King Room,2,Low-quality food,0,13.0
16,Club Deluxe King Room,2,Noisy neighbors,0,3.0
17,Club Deluxe King Room,2,"Rodents, roaches, & other unwanted guests",0,1.0
18,Club Deluxe King Room,2,Slow Wi-Fi,0,3.0
19,Club Deluxe King Room,2,Temperature of their room,0,1.0
20,Club Deluxe King Room,2,Issues with staff,0,2.0
21,Club Deluxe King Room,2,No hot water,0,4.0
22,Club Deluxe King Room,3,Bad smells,0,4.0
23,Club Deluxe King Room,3,Dirty rooms,0,3.0
24,Club Deluxe King Room,3,Doesn’t match the website/brochure,0,5.0
25,Club Deluxe King Room,3,Faulty electronics,0,9.0
26,Club Deluxe King Room,3,Low-quality food,0,12.0
27,Club Deluxe King Room,3,Noisy neighbors,0,4.0
28,Club Deluxe King Room,3,"Rodents, roaches, & other unwanted guests",0,3.0
29,Club Deluxe King Room,3,Slow Wi-Fi,0,4.0
30,Club Deluxe King Room,3,Temperature of their room,0,2.0
31,Club Deluxe King Room,3,Issues with staff,0,2.0
32,Club Deluxe King Room,3,No hot water,0,2.0
33,Club Deluxe King Room,4,Bad smells,0,1.0
34,Club Deluxe King Room,4,Dirty rooms,0,3.0
35,Club Deluxe King Room,4,Doesn’t match the website/brochure,0,5.0
36,Club Deluxe King Room,4,Faulty electronics,0,7.0
37,Club Deluxe King Room,4,Low-quality food,0,5.0
38,Club Deluxe King Room,4,Noisy neighbors,0,3.0
39,Club Deluxe King Room,4,"Rodents, roaches, & other unwanted guests",0,3.0
40,Club Deluxe King Room,4,Slow Wi-Fi,0,NaN
41,Club Deluxe King Room,4,Temperature of their room,0,1.0
42,Club Deluxe King Room,4,Issues with staff,0,1.0
43,Club Deluxe King Room,4,No hot water,0,NaN
44,Club Deluxe King Room,5,Bad smells,0,2.0
45,Club Deluxe King Room,5,Dirty rooms,0,2.0
46,Club Deluxe King Room,5,Doesn’t match the website/brochure,0,5.0
47,Club Deluxe King Room,5,Faulty electronics,0,4.0
48,Club Deluxe King Room,5,Low-quality food,0,2.0
49,Club Deluxe King Room,5,Noisy neighbors,0,4.0
50,Club Deluxe King Room,5,"Rodents, roaches, & other unwanted guests",0,1.0
51,Club Deluxe King Room,5,Slow Wi-Fi,0,4.0
52,Club Deluxe King Room,5,Temperature of their room,0,1.0
53,Club Deluxe King Room,5,Issues with staff,0,3.0
54,Club Deluxe King Room,5,No hot water,0,2.0
55,Club Deluxe King Room,6,Bad smells,0,1.0
56,Club Deluxe King Room,6,Dirty rooms,0,2.0
57,Club Deluxe King Room,6,Doesn’t match the website/brochure,0,2.0
58,Club Deluxe King Room,6,Faulty electronics,0,5.0
59,Club Deluxe King Room,6,Low-quality food,0,2.0
60,Club Deluxe King Room,6,Noisy neighbors,0,NaN
61,Club Deluxe King Room,6,"Rodents, roaches, & other unwanted guests",0,NaN
62,Club Deluxe King Room,6,Slow Wi-Fi,0,NaN
63,Club Deluxe King Room,6,Temperature of their room,0,2.0
64,Club Deluxe King Room,6,Issues with staff,0,1.0
65,Club Deluxe King Room,6,No hot water,0,2.0
66,Club Deluxe King Room,7,Bad smells,0,4.0
67,Club Deluxe King Room,7,Dirty rooms,0,NaN
68,Club Deluxe King Room,7,Doesn’t match the website/brochure,0,7.0
69,Club Deluxe King Room,7,Faulty electronics,0,4.0
70,Club Deluxe King Room,7,Low-quality food,0,NaN
71,Club Deluxe King Room,7,Noisy neighbors,0,2.0
72,Club Deluxe King Room,7,"Rodents, roaches, & other unwanted guests",0,4.0
73,Club Deluxe King Room,7,Slow Wi-Fi,0,4.0
74,Club Deluxe King Room,7,Temperature of their room,0,3.0
75,Club Deluxe King Room,7,Issues with staff,0,4.0
76,Club Deluxe King Room,7,No hot water,0,4.0
77,Club Deluxe King Room,8,Bad smells,0,3.0
78,Club Deluxe King Room,8,Dirty rooms,0,1.0
79,Club Deluxe King Room,8,Doesn’t match the website/brochure,0,3.0
80,Club Deluxe King Room,8,Faulty electronics,0,4.0
81,Club Deluxe King Room,8,Low-quality food,0,3.0
82,Club Deluxe King Room,8,Noisy neighbors,0,2.0
83,Club Deluxe King Room,8,"Rodents, roaches, & other unwanted guests",0,2.0
84,Club Deluxe King Room,8,Slow Wi-Fi,0,2.0
85,Club Deluxe King Room,8,Temperature of their room,0,NaN
86,Club Deluxe King Room,8,Issues with staff,0,1.0
87,Club Deluxe King Room,8,No hot water,0,4.0
88,Club Deluxe King Room,9,Bad smells,0,2.0
89,Club Deluxe King Room,9,Dirty rooms,0,4.0
90,Club Deluxe King Room,9,Doesn’t match the website/brochure,0,4.0
91,Club Deluxe King Room,9,Faulty electronics,0,7.0
92,Club Deluxe King Room,9,Low-quality food,0,1.0
93,Club Deluxe King Room,9,Noisy neighbors,0,4.0
94,Club Deluxe King Room,9,"Rodents, roaches, & other unwanted guests",0,3.0
95,Club Deluxe King Room,9,Slow Wi-Fi,0,1.0
96,Club Deluxe King Room,9,Temperature of their room,0,3.0
97,Club Deluxe King Room,9,Issues with staff,0,2.0
98,Club Deluxe King Room,9,No hot water,0,3.0
99,Club Deluxe King Room,10,Bad smells,0,6.0
100,Club Deluxe King Room,10,Dirty rooms,0,2.0
101,Club Deluxe King Room,10,Doesn’t match the website/brochure,0,6.0
102,Club Deluxe King Room,10,Faulty electronics,0,3.0
103,Club Deluxe King Room,10,Low-quality food,0,NaN
104,Club Deluxe King Room,10,Noisy neighbors,0,5.0
105,Club Deluxe King Room,10,"Rodents, roaches, & other unwanted guests",0,1.0
106,Club Deluxe King Room,10,Slow Wi-Fi,0,1.0
107,Club Deluxe King Room,10,Temperature of their room,0,3.0
108,Club Deluxe King Room,10,Issues with staff,0,2.0
109,Club Deluxe King Room,10,No hot water,0,1.0
110,Club Deluxe King Room,11,Bad smells,0,4.0
111,Club Deluxe King Room,11,Dirty rooms,0,3.0
112,Club Deluxe King Room,11,Doesn’t match the website/brochure,0,2.0
113,Club Deluxe King Room,11,Faulty electronics,0,3.0
114,Club Deluxe King Room,11,Low-quality food,0,1.0
115,Club Deluxe King Room,11,Noisy neighbors,0,5.0
116,Club Deluxe King Room,11,"Rodents, roaches, & other unwanted guests",0,2.0
117,Club Deluxe King Room,11,Slow Wi-Fi,0,4.0
118,Club Deluxe King Room,11,Temperature of their room,0,1.0
119,Club Deluxe King Room,11,Issues with staff,0,NaN
120,Club Deluxe King Room,11,No hot water,0,1.0
121,Club Deluxe King Room,12,Bad smells,0,NaN
122,Club Deluxe King Room,12,Dirty rooms,0,1.0
123,Club Deluxe King Room,12,Doesn’t match the website/brochure,0,5.0
124,Club Deluxe King Room,12,Faulty electronics,0,NaN
125,Club Deluxe King Room,12,Low-quality food,0,1.0
126,Club Deluxe King Room,12,Noisy neighbors,0,6.0
127,Club Deluxe King Room,12,"Rodents, roaches, & other unwanted guests",0,1.0
128,Club Deluxe King Room,12,Slow Wi-Fi,0,2.0
129,Club Deluxe King Room,12,Temperature of their room,0,NaN
130,Club Deluxe King Room,12,Issues with staff,0,3.0
131,Club Deluxe King Room,12,No hot water,0,NaN
132,Executive Suite,1,Bad smells,0,6.0
133,Executive Suite,1,Dirty rooms,0,3.0
134,Executive Suite,1,Doesn’t match the website/brochure,0,6.0
135,Executive Suite,1,Faulty electronics,0,6.0
136,Executive Suite,1,Low-quality food,0,3.0
137,Executive Suite,1,Noisy neighbors,0,5.0
138,Executive Suite,1,"Rodents, roaches, & other unwanted guests",0,2.0
139,Executive Suite,1,Slow Wi-Fi,0,6.0
140,Executive Suite,1,Temperature of their room,0,1.0
141,Executive Suite,1,Issues with staff,0,3.0
142,Executive Suite,1,No hot water,0,3.0
143,Executive Suite,2,Bad smells,0,2.0
144,Executive Suite,2,Dirty rooms,0,1.0
145,Executive Suite,2,Doesn’t match the website/brochure,0,3.0
146,Executive Suite,2,Faulty electronics,0,1.0
147,Executive Suite,2,Low-quality food,0,3.0
148,Executive Suite,2,Noisy neighbors,0,7.0
149,Executive Suite,2,"Rodents, roaches, & other unwanted guests",0,1.0
150,Executive Suite,2,Slow Wi-Fi,0,3.0
151,Executive Suite,2,Temperature of their room,0,1.0
152,Executive Suite,2,Issues with staff,0,NaN
153,Executive Suite,2,No hot water,0,1.0
154,Executive Suite,3,Bad smells,0,5.0
155,Executive Suite,3,Dirty rooms,0,2.0
156,Executive Suite,3,Doesn’t match the website/brochure,0,5.0
157,Executive Suite,3,Faulty electronics,0,10.0
158,Executive Suite,3,Low-quality food,0,NaN
159,Executive Suite,3,Noisy neighbors,0,3.0
160,Executive Suite,3,"Rodents, roaches, & other unwanted guests",0,1.0
161,Executive Suite,3,Slow Wi-Fi,0,1.0
162,Executive Suite,3,Temperature of their room,0,1.0
163,Executive Suite,3,Issues with staff,0,NaN
164,Executive Suite,3,No hot water,0,4.0
165,Executive Suite,4,Bad smells,0,4.0
166,Executive Suite,4,Dirty rooms,0,2.0
167,Executive Suite,4,Doesn’t match the website/brochure,0,6.0
168,Executive Suite,4,Faulty electronics,0,3.0
169,Executive Suite,4,Low-quality food,0,1.0
170,Executive Suite,4,Noisy neighbors,0,5.0
171,Executive Suite,4,"Rodents, roaches, & other unwanted guests",0,1.0
172,Executive Suite,4,Slow Wi-Fi,0,3.0
173,Executive Suite,4,Temperature of their room,0,3.0
174,Executive Suite,4,Issues with staff,0,1.0
175,Executive Suite,4,No hot water,0,1.0
176,Executive Suite,5,Bad smells,0,1.0
177,Executive Suite,5,Dirty rooms,0,1.0
178,Executive Suite,5,Doesn’t match the website/brochure,0,7.0
179,Executive Suite,5,Faulty electronics,0,2.0
180,Executive Suite,5,Low-quality food,0,2.0
181,Executive Suite,5,Noisy neighbors,0,6.0
182,Executive Suite,5,"Rodents, roaches, & other unwanted guests",0,2.0
183,Executive Suite,5,Slow Wi-Fi,0,2.0
184,Executive Suite,5,Temperature of their room,0,3.0
185,Executive Suite,5,Issues with staff,0,NaN
186,Executive Suite,5,No hot water,0,2.0
187,Executive Suite,6,Bad smells,0,NaN
188,Executive Suite,6,Dirty rooms,0,1.0
189,Executive Suite,6,Doesn’t match the website/brochure,0,2.0
190,Executive Suite,6,Faulty electronics,0,3.0
191,Executive Suite,6,Low-quality food,0,NaN
192,Executive Suite,6,Noisy neighbors,0,1.0
193,Executive Suite,6,"Rodents, roaches, & other unwanted guests",0,1.0
194,Executive Suite,6,Slow Wi-Fi,0,3.0
195,Executive Suite,6,Temperature of their room,0,NaN
196,Executive Suite,6,Issues with staff,0,1.0
197,Executive Suite,6,No hot water,0,1.0
198,Executive Suite,7,Bad smells,0,3.0
199,Executive Suite,7,Dirty rooms,0,NaN
200,Executive Suite,7,Doesn’t match the website/brochure,0,6.0
201,Executive Suite,7,Faulty electronics,0,2.0
202,Executive Suite,7,Low-quality food,0,NaN
203,Executive Suite,7,Noisy neighbors,0,NaN
204,Executive Suite,7,"Rodents, roaches, & other unwanted guests",0,3.0
205,Executive Suite,7,Slow Wi-Fi,0,2.0
206,Executive Suite,7,Temperature of their room,0,3.0
207,Executive Suite,7,Issues with staff,0,4.0
208,Executive Suite,7,No hot water,0,2.0
209,Executive Suite,8,Bad smells,0,2.0
210,Executive Suite,8,Dirty rooms,0,1.0
211,Executive Suite,8,Doesn’t match the website/brochure,0,3.0
212,Executive Suite,8,Faulty electronics,0,5.0
213,Executive Suite,8,Low-quality food,0,2.0
214,Executive Suite,8,Noisy neighbors,0,4.0
215,Executive Suite,8,"Rodents, roaches, & other unwanted guests",0,3.0
216,Executive Suite,8,Slow Wi-Fi,0,1.0
217,Executive Suite,8,Temperature of their room,0,2.0
218,Executive Suite,8,Issues with staff,0,1.0
219,Executive Suite,8,No hot water,0,4.0
220,Executive Suite,9,Bad smells,0,2.0
221,Executive Suite,9,Dirty rooms,0,1.0
222,Executive Suite,9,Doesn’t match the website/brochure,0,1.0
223,Executive Suite,9,Faulty electronics,0,1.0
224,Executive Suite,9,Low-quality food,0,1.0
225,Executive Suite,9,Noisy neighbors,0,3.0
226,Executive Suite,9,"Rodents, roaches, & other unwanted guests",0,NaN
227,Executive Suite,9,Slow Wi-Fi,0,4.0
228,Executive Suite,9,Temperature of their room,0,2.0
229,Executive Suite,9,Issues with staff,0,4.0
230,Executive Suite,9,No hot water,0,NaN
231,Executive Suite,10,Bad smells,0,2.0
232,Executive Suite,10,Dirty rooms,0,2.0
233,Executive Suite,10,Doesn’t match the website/brochure,0,4.0
234,Executive Suite,10,Faulty electronics,0,4.0
235,Executive Suite,10,Low-quality food,0,4.0
236,Executive Suite,10,Noisy neighbors,0,4.0
237,Executive Suite,10,"Rodents, roaches, & other unwanted guests",0,3.0
238,Executive Suite,10,Slow Wi-Fi,0,3.0
239,Executive Suite,10,Temperature of their room,0,2.0
240,Executive Suite,10,Issues with staff,0,2.0
241,Executive Suite,10,No hot water,0,6.0
242,Executive Suite,11,Bad smells,0,1.0
243,Executive Suite,11,Dirty rooms,0,2.0
244,Executive Suite,11,Doesn’t match the website/brochure,0,1.0
245,Executive Suite,11,Faulty electronics,0,1.0
246,Executive Suite,11,Low-quality food,0,2.0
247,Executive Suite,11,Noisy neighbors,0,5.0
248,Executive Suite,11,"Rodents, roaches, & other unwanted guests",0,NaN
249,Executive Suite,11,Slow Wi-Fi,0,3.0
250,Executive Suite,11,Temperature of their room,0,1.0
251,Executive Suite,11,Issues with staff,0,3.0
252,Executive Suite,11,No hot water,0,1.0
253,Executive Suite,12,Bad smells,0,1.0
254,Executive Suite,12,Dirty rooms,0,2.0
255,Executive Suite,12,Doesn’t match the website/brochure,0,3.0
256,Executive Suite,12,Faulty electronics,0,6.0
257,Executive Suite,12,Low-quality food,0,3.0
258,Executive Suite,12,Noisy neighbors,0,2.0
259,Executive Suite,12,"Rodents, roaches, & other unwanted guests",0,3.0
260,Executive Suite,12,Slow Wi-Fi,0,1.0
261,Executive Suite,12,Temperature of their room,0,1.0
262,Executive Suite,12,Issues with staff,0,4.0
263,Executive Suite,12,No hot water,0,4.0
264,King Suite,1,Bad smells,0,11.0
265,King Suite,1,Dirty rooms,0,5.0
266,King Suite,1,Doesn’t match the website/brochure,0,5.0
267,King Suite,1,Faulty electronics,0,14.0
268,King Suite,1,Low-quality food,0,9.0
269,King Suite,1,Noisy neighbors,0,17.0
270,King Suite,1,"Rodents, roaches, & other unwanted guests",0,9.0
271,King Suite,1,Slow Wi-Fi,0,6.0
272,King Suite,1,Temperature of their room,0,4.0
273,King Suite,1,Issues with staff,0,4.0
274,King Suite,1,No hot water,0,11.0
275,King Suite,2,Bad smells,0,8.0
276,King Suite,2,Dirty rooms,0,6.0
277,King Suite,2,Doesn’t match the website/brochure,0,2.0
278,King Suite,2,Faulty electronics,0,7.0
279,King Suite,2,Low-quality food,0,2.0
280,King Suite,2,Noisy neighbors,0,13.0
281,King Suite,2,"Rodents, roaches, & other unwanted guests",0,4.0
282,King Suite,2,Slow Wi-Fi,0,5.0
283,King Suite,2,Temperature of their room,0,2.0
284,King Suite,2,Issues with staff,0,4.0
285,King Suite,2,No hot water,0,9.0
286,King Suite,3,Bad smells,0,2.0
287,King Suite,3,Dirty rooms,0,NaN
288,King Suite,3,Doesn’t match the website/brochure,0,3.0
289,King Suite,3,Faulty electronics,0,5.0
290,King Suite,3,Low-quality food,0,2.0
291,King Suite,3,Noisy neighbors,0,14.0
292,King Suite,3,"Rodents, roaches, & other unwanted guests",0,4.0
293,King Suite,3,Slow Wi-Fi,0,5.0
294,King Suite,3,Temperature of their room,0,4.0
295,King Suite,3,Issues with staff,0,NaN
296,King Suite,3,No hot water,0,3.0
297,King Suite,4,Bad smells,0,3.0
298,King Suite,4,Dirty rooms,0,2.0
299,King Suite,4,Doesn’t match the website/brochure,0,2.0
300,King Suite,4,Faulty electronics,0,3.0
301,King Suite,4,Low-quality food,0,1.0
302,King Suite,4,Noisy neighbors,0,8.0
303,King Suite,4,"Rodents, roaches, & other unwanted guests",0,1.0
304,King Suite,4,Slow Wi-Fi,0,NaN
305,King Suite,4,Temperature of their room,0,2.0
306,King Suite,4,Issues with staff,0,3.0
307,King Suite,4,No hot water,0,3.0
308,King Suite,5,Bad smells,0,5.0
309,King Suite,5,Dirty rooms,0,2.0
310,King Suite,5,Doesn’t match the website/brochure,0,1.0
311,King Suite,5,Faulty electronics,0,1.0
312,King Suite,5,Low-quality food,0,1.0
313,King Suite,5,Noisy neighbors,0,3.0
314,King Suite,5,"Rodents, roaches, & other unwanted guests",0,1.0
315,King Suite,5,Slow Wi-Fi,0,2.0
316,King Suite,5,Temperature of their room,0,1.0
317,King Suite,5,Issues with staff,0,1.0
318,King Suite,5,No hot water,0,1.0
319,King Suite,6,Bad smells,0,2.0
320,King Suite,6,Dirty rooms,0,2.0
321,King Suite,6,Doesn’t match the website/brochure,0,1.0
322,King Suite,6,Faulty electronics,0,NaN
323,King Suite,6,Low-quality food,0,NaN
324,King Suite,6,Noisy neighbors,0,3.0
325,King Suite,6,"Rodents, roaches, & other unwanted guests",0,1.0
326,King Suite,6,Slow Wi-Fi,0,1.0
327,King Suite,6,Temperature of their room,0,2.0
328,King Suite,6,Issues with staff,0,NaN
329,King Suite,6,No hot water,0,NaN
330,King Suite,7,Bad smells,0,5.0
331,King Suite,7,Dirty rooms,0,NaN
332,King Suite,7,Doesn’t match the website/brochure,0,1.0
333,King Suite,7,Faulty electronics,0,3.0
334,King Suite,7,Low-quality food,0,2.0
335,King Suite,7,Noisy neighbors,0,6.0
336,King Suite,7,"Rodents, roaches, & other unwanted guests",0,4.0
337,King Suite,7,Slow Wi-Fi,0,1.0
338,King Suite,7,Temperature of their room,0,56.0
339,King Suite,7,Issues with staff,0,4.0
340,King Suite,7,No hot water,0,2.0
341,King Suite,8,Bad smells,0,2.0
342,King Suite,8,Dirty rooms,0,1.0
343,King Suite,8,Doesn’t match the website/brochure,0,1.0
344,King Suite,8,Faulty electronics,0,NaN
345,King Suite,8,Low-quality food,0,2.0
346,King Suite,8,Noisy neighbors,0,8.0
347,King Suite,8,"Rodents, roaches, & other unwanted guests",0,3.0
348,King Suite,8,Slow Wi-Fi,0,3.0
349,King Suite,8,Temperature of their room,0,71.0
350,King Suite,8,Issues with staff,0,NaN
351,King Suite,8,No hot water,0,2.0
352,King Suite,9,Bad smells,0,5.0
353,King Suite,9,Dirty rooms,0,NaN
354,King Suite,9,Doesn’t match the website/brochure,0,4.0
355,King Suite,9,Faulty electronics,0,1.0
356,King Suite,9,Low-quality food,0,2.0
357,King Suite,9,Noisy neighbors,0,8.0
358,King Suite,9,"Rodents, roaches, & other unwanted guests",0,3.0
359,King Suite,9,Slow Wi-Fi,0,8.0
360,King Suite,9,Temperature of their room,0,97.0
361,King Suite,9,Issues with staff,0,1.0
362,King Suite,9,No hot water,0,NaN
363,King Suite,10,Bad smells,0,NaN
364,King Suite,10,Dirty rooms,0,1.0
365,King Suite,10,Doesn’t match the website/brochure,0,1.0
366,King Suite,10,Faulty electronics,0,2.0
367,King Suite,10,Low-quality food,0,1.0
368,King Suite,10,Noisy neighbors,0,3.0
369,King Suite,10,"Rodents, roaches, & other unwanted guests",0,1.0
370,King Suite,10,Slow Wi-Fi,0,5.0
371,King Suite,10,Temperature of their room,0,50.0
372,King Suite,10,Issues with staff,0,1.0
373,King Suite,10,No hot water,0,2.0
374,King Suite,11,Bad smells,0,3.0
375,King Suite,11,Dirty rooms,0,1.0
376,King Suite,11,Doesn’t match the website/brochure,0,2.0
377,King Suite,11,Faulty electronics,0,2.0
378,King Suite,11,Low-quality food,0,NaN
379,King Suite,11,Noisy neighbors,0,5.0
380,King Suite,11,"Rodents, roaches, & other unwanted guests",0,NaN
381,King Suite,11,Slow Wi-Fi,0,2.0
382,King Suite,11,Temperature of their room,0,52.0
383,King Suite,11,Issues with staff,0,NaN
384,King Suite,11,No hot water,0,1.0
385,King Suite,12,Bad smells,0,1.0
386,King Suite,12,Dirty rooms,0,NaN
387,King Suite,12,Doesn’t match the website/brochure,0,2.0
388,King Suite,12,Faulty electronics,0,4.0
389,King Suite,12,Low-quality food,0,NaN
390,King Suite,12,Noisy neighbors,0,5.0
391,King Suite,12,"Rodents, roaches, & other unwanted guests",0,3.0
392,King Suite,12,Slow Wi-Fi,0,5.0
393,King Suite,12,Temperature of their room,0,54.0
394,King Suite,12,Issues with staff,0,2.0
395,King Suite,12,No hot water,0,2.0
396,One-Bedroom Club Room,1,Bad smells,0,1.0
397,One-Bedroom Club Room,1,Dirty rooms,0,1.0
398,One-Bedroom Club Room,1,Doesn’t match the website/brochure,0,1.0
399,One-Bedroom Club Room,1,Faulty electronics,0,2.0
400,One-Bedroom Club Room,1,Low-quality food,0,6.0
401,One-Bedroom Club Room,1,Noisy neighbors,0,NaN
402,One-Bedroom Club Room,1,"Rodents, roaches, & other unwanted guests",0,2.0
403,One-Bedroom Club Room,1,Slow Wi-Fi,0,NaN
404,One-Bedroom Club Room,1,Temperature of their room,0,NaN
405,One-Bedroom Club Room,1,Issues with staff,0,4.0
406,One-Bedroom Club Room,1,No hot water,0,NaN
407,One-Bedroom Club Room,2,Bad smells,0,NaN
408,One-Bedroom Club Room,2,Dirty rooms,0,1.0

In [97]:
ts.loc[ts["size"].notnull(),"Count"]=ts["size"]

In [100]:
ts = ts.drop(columns="size")

In [101]:
ts

,Room type,Month,Concern description,Count
0,Club Deluxe King Room,1,Bad smells,1.0
1,Club Deluxe King Room,1,Dirty rooms,2.0
2,Club Deluxe King Room,1,Doesn’t match the website/brochure,4.0
3,Club Deluxe King Room,1,Faulty electronics,5.0
4,Club Deluxe King Room,1,Low-quality food,13.0
5,Club Deluxe King Room,1,Noisy neighbors,3.0
6,Club Deluxe King Room,1,"Rodents, roaches, & other unwanted guests",2.0
7,Club Deluxe King Room,1,Slow Wi-Fi,2.0
8,Club Deluxe King Room,1,Temperature of their room,2.0
9,Club Deluxe King Room,1,Issues with staff,0.0
10,Club Deluxe King Room,1,No hot water,0.0
11,Club Deluxe King Room,2,Bad smells,2.0
12,Club Deluxe King Room,2,Dirty rooms,0.0
13,Club Deluxe King Room,2,Doesn’t match the website/brochure,5.0
14,Club Deluxe King Room,2,Faulty electronics,4.0
15,Club Deluxe King Room,2,Low-quality food,13.0
16,Club Deluxe King Room,2,Noisy neighbors,3.0
17,Club Deluxe King Room,2,"Rodents, roaches, & other unwanted guests",1.0
18,Club Deluxe King Room,2,Slow Wi-Fi,3.0
19,Club Deluxe King Room,2,Temperature of their room,1.0
20,Club Deluxe King Room,2,Issues with staff,2.0
21,Club Deluxe King Room,2,No hot water,4.0
22,Club Deluxe King Room,3,Bad smells,4.0
23,Club Deluxe King Room,3,Dirty rooms,3.0
24,Club Deluxe King Room,3,Doesn’t match the website/brochure,5.0
25,Club Deluxe King Room,3,Faulty electronics,9.0
26,Club Deluxe King Room,3,Low-quality food,12.0
27,Club Deluxe King Room,3,Noisy neighbors,4.0
28,Club Deluxe King Room,3,"Rodents, roaches, & other unwanted guests",3.0
29,Club Deluxe King Room,3,Slow Wi-Fi,4.0
30,Club Deluxe King Room,3,Temperature of their room,2.0
31,Club Deluxe King Room,3,Issues with staff,2.0
32,Club Deluxe King Room,3,No hot water,2.0
33,Club Deluxe King Room,4,Bad smells,1.0
34,Club Deluxe King Room,4,Dirty rooms,3.0
35,Club Deluxe King Room,4,Doesn’t match the website/brochure,5.0
36,Club Deluxe King Room,4,Faulty electronics,7.0
37,Club Deluxe King Room,4,Low-quality food,5.0
38,Club Deluxe King Room,4,Noisy neighbors,3.0
39,Club Deluxe King Room,4,"Rodents, roaches, & other unwanted guests",3.0
40,Club Deluxe King Room,4,Slow Wi-Fi,0.0
41,Club Deluxe King Room,4,Temperature of their room,1.0
42,Club Deluxe King Room,4,Issues with staff,1.0
43,Club Deluxe King Room,4,No hot water,0.0
44,Club Deluxe King Room,5,Bad smells,2.0
45,Club Deluxe King Room,5,Dirty rooms,2.0
46,Club Deluxe King Room,5,Doesn’t match the website/brochure,5.0
47,Club Deluxe King Room,5,Faulty electronics,4.0
48,Club Deluxe King Room,5,Low-quality food,2.0
49,Club Deluxe King Room,5,Noisy neighbors,4.0
50,Club Deluxe King Room,5,"Rodents, roaches, & other unwanted guests",1.0
51,Club Deluxe King Room,5,Slow Wi-Fi,4.0
52,Club Deluxe King Room,5,Temperature of their room,1.0
53,Club Deluxe King Room,5,Issues with staff,3.0
54,Club Deluxe King Room,5,No hot water,2.0
55,Club Deluxe King Room,6,Bad smells,1.0
56,Club Deluxe King Room,6,Dirty rooms,2.0
57,Club Deluxe King Room,6,Doesn’t match the website/brochure,2.0
58,Club Deluxe King Room,6,Faulty electronics,5.0
59,Club Deluxe King Room,6,Low-quality food,2.0
60,Club Deluxe King Room,6,Noisy neighbors,0.0
61,Club Deluxe King Room,6,"Rodents, roaches, & other unwanted guests",0.0
62,Club Deluxe King Room,6,Slow Wi-Fi,0.0
63,Club Deluxe King Room,6,Temperature of their room,2.0
64,Club Deluxe King Room,6,Issues with staff,1.0
65,Club Deluxe King Room,6,No hot water,2.0
66,Club Deluxe King Room,7,Bad smells,4.0
67,Club Deluxe King Room,7,Dirty rooms,0.0
68,Club Deluxe King Room,7,Doesn’t match the website/brochure,7.0
69,Club Deluxe King Room,7,Faulty electronics,4.0
70,Club Deluxe King Room,7,Low-quality food,0.0
71,Club Deluxe King Room,7,Noisy neighbors,2.0
72,Club Deluxe King Room,7,"Rodents, roaches, & other unwanted guests",4.0
73,Club Deluxe King Room,7,Slow Wi-Fi,4.0
74,Club Deluxe King Room,7,Temperature of their room,3.0
75,Club Deluxe King Room,7,Issues with staff,4.0
76,Club Deluxe King Room,7,No hot water,4.0
77,Club Deluxe King Room,8,Bad smells,3.0
78,Club Deluxe King Room,8,Dirty rooms,1.0
79,Club Deluxe King Room,8,Doesn’t match the website/brochure,3.0
80,Club Deluxe King Room,8,Faulty electronics,4.0
81,Club Deluxe King Room,8,Low-quality food,3.0
82,Club Deluxe King Room,8,Noisy neighbors,2.0
83,Club Deluxe King Room,8,"Rodents, roaches, & other unwanted guests",2.0
84,Club Deluxe King Room,8,Slow Wi-Fi,2.0
85,Club Deluxe King Room,8,Temperature of their room,0.0
86,Club Deluxe King Room,8,Issues with staff,1.0
87,Club Deluxe King Room,8,No hot water,4.0
88,Club Deluxe King Room,9,Bad smells,2.0
89,Club Deluxe King Room,9,Dirty rooms,4.0
90,Club Deluxe King Room,9,Doesn’t match the website/brochure,4.0
91,Club Deluxe King Room,9,Faulty electronics,7.0
92,Club Deluxe King Room,9,Low-quality food,1.0
93,Club Deluxe King Room,9,Noisy neighbors,4.0
94,Club Deluxe King Room,9,"Rodents, roaches, & other unwanted guests",3.0
95,Club Deluxe King Room,9,Slow Wi-Fi,1.0
96,Club Deluxe King Room,9,Temperature of their room,3.0
97,Club Deluxe King Room,9,Issues with staff,2.0
98,Club Deluxe King Room,9,No hot water,3.0
99,Club Deluxe King Room,10,Bad smells,6.0
100,Club Deluxe King Room,10,Dirty rooms,2.0
101,Club Deluxe King Room,10,Doesn’t match the website/brochure,6.0
102,Club Deluxe King Room,10,Faulty electronics,3.0
103,Club Deluxe King Room,10,Low-quality food,0.0
104,Club Deluxe King Room,10,Noisy neighbors,5.0
105,Club Deluxe King Room,10,"Rodents, roaches, & other unwanted guests",1.0
106,Club Deluxe King Room,10,Slow Wi-Fi,1.0
107,Club Deluxe King Room,10,Temperature of their room,3.0
108,Club Deluxe King Room,10,Issues with staff,2.0
109,Club Deluxe King Room,10,No hot water,1.0
110,Club Deluxe King Room,11,Bad smells,4.0
111,Club Deluxe King Room,11,Dirty rooms,3.0
112,Club Deluxe King Room,11,Doesn’t match the website/brochure,2.0
113,Club Deluxe King Room,11,Faulty electronics,3.0
114,Club Deluxe King Room,11,Low-quality food,1.0
115,Club Deluxe King Room,11,Noisy neighbors,5.0
116,Club Deluxe King Room,11,"Rodents, roaches, & other unwanted guests",2.0
117,Club Deluxe King Room,11,Slow Wi-Fi,4.0
118,Club Deluxe King Room,11,Temperature of their room,1.0
119,Club Deluxe King Room,11,Issues with staff,0.0
120,Club Deluxe King Room,11,No hot water,1.0
121,Club Deluxe King Room,12,Bad smells,0.0
122,Club Deluxe King Room,12,Dirty rooms,1.0
123,Club Deluxe King Room,12,Doesn’t match the website/brochure,5.0
124,Club Deluxe King Room,12,Faulty electronics,0.0
125,Club Deluxe King Room,12,Low-quality food,1.0
126,Club Deluxe King Room,12,Noisy neighbors,6.0
127,Club Deluxe King Room,12,"Rodents, roaches, & other unwanted guests",1.0
128,Club Deluxe King Room,12,Slow Wi-Fi,2.0
129,Club Deluxe King Room,12,Temperature of their room,0.0
130,Club Deluxe King Room,12,Issues with staff,3.0
131,Club Deluxe King Room,12,No hot water,0.0
132,Executive Suite,1,Bad smells,6.0
133,Executive Suite,1,Dirty rooms,3.0
134,Executive Suite,1,Doesn’t match the website/brochure,6.0
135,Executive Suite,1,Faulty electronics,6.0
136,Executive Suite,1,Low-quality food,3.0
137,Executive Suite,1,Noisy neighbors,5.0
138,Executive Suite,1,"Rodents, roaches, & other unwanted guests",2.0
139,Executive Suite,1,Slow Wi-Fi,6.0
140,Executive Suite,1,Temperature of their room,1.0
141,Executive Suite,1,Issues with staff,3.0
142,Executive Suite,1,No hot water,3.0
143,Executive Suite,2,Bad smells,2.0
144,Executive Suite,2,Dirty rooms,1.0
145,Executive Suite,2,Doesn’t match the website/brochure,3.0
146,Executive Suite,2,Faulty electronics,1.0
147,Executive Suite,2,Low-quality food,3.0
148,Executive Suite,2,Noisy neighbors,7.0
149,Executive Suite,2,"Rodents, roaches, & other unwanted guests",1.0
150,Executive Suite,2,Slow Wi-Fi,3.0
151,Executive Suite,2,Temperature of their room,1.0
152,Executive Suite,2,Issues with staff,0.0
153,Executive Suite,2,No hot water,1.0
154,Executive Suite,3,Bad smells,5.0
155,Executive Suite,3,Dirty rooms,2.0
156,Executive Suite,3,Doesn’t match the website/brochure,5.0
157,Executive Suite,3,Faulty electronics,10.0
158,Executive Suite,3,Low-quality food,0.0
159,Executive Suite,3,Noisy neighbors,3.0
160,Executive Suite,3,"Rodents, roaches, & other unwanted guests",1.0
161,Executive Suite,3,Slow Wi-Fi,1.0
162,Executive Suite,3,Temperature of their room,1.0
163,Executive Suite,3,Issues with staff,0.0
164,Executive Suite,3,No hot water,4.0
165,Executive Suite,4,Bad smells,4.0
166,Executive Suite,4,Dirty rooms,2.0
167,Executive Suite,4,Doesn’t match the website/brochure,6.0
168,Executive Suite,4,Faulty electronics,3.0
169,Executive Suite,4,Low-quality food,1.0
170,Executive Suite,4,Noisy neighbors,5.0
171,Executive Suite,4,"Rodents, roaches, & other unwanted guests",1.0
172,Executive Suite,4,Slow Wi-Fi,3.0
173,Executive Suite,4,Temperature of their room,3.0
174,Executive Suite,4,Issues with staff,1.0
175,Executive Suite,4,No hot water,1.0
176,Executive Suite,5,Bad smells,1.0
177,Executive Suite,5,Dirty rooms,1.0
178,Executive Suite,5,Doesn’t match the website/brochure,7.0
179,Executive Suite,5,Faulty electronics,2.0
180,Executive Suite,5,Low-quality food,2.0
181,Executive Suite,5,Noisy neighbors,6.0
182,Executive Suite,5,"Rodents, roaches, & other unwanted guests",2.0
183,Executive Suite,5,Slow Wi-Fi,2.0
184,Executive Suite,5,Temperature of their room,3.0
185,Executive Suite,5,Issues with staff,0.0
186,Executive Suite,5,No hot water,2.0
187,Executive Suite,6,Bad smells,0.0
188,Executive Suite,6,Dirty rooms,1.0
189,Executive Suite,6,Doesn’t match the website/brochure,2.0
190,Executive Suite,6,Faulty electronics,3.0
191,Executive Suite,6,Low-quality food,0.0
192,Executive Suite,6,Noisy neighbors,1.0
193,Executive Suite,6,"Rodents, roaches, & other unwanted guests",1.0
194,Executive Suite,6,Slow Wi-Fi,3.0
195,Executive Suite,6,Temperature of their room,0.0
196,Executive Suite,6,Issues with staff,1.0
197,Executive Suite,6,No hot water,1.0
198,Executive Suite,7,Bad smells,3.0
199,Executive Suite,7,Dirty rooms,0.0
200,Executive Suite,7,Doesn’t match the website/brochure,6.0
201,Executive Suite,7,Faulty electronics,2.0
202,Executive Suite,7,Low-quality food,0.0
203,Executive Suite,7,Noisy neighbors,0.0
204,Executive Suite,7,"Rodents, roaches, & other unwanted guests",3.0
205,Executive Suite,7,Slow Wi-Fi,2.0
206,Executive Suite,7,Temperature of their room,3.0
207,Executive Suite,7,Issues with staff,4.0
208,Executive Suite,7,No hot water,2.0
209,Executive Suite,8,Bad smells,2.0
210,Executive Suite,8,Dirty rooms,1.0
211,Executive Suite,8,Doesn’t match the website/brochure,3.0
212,Executive Suite,8,Faulty electronics,5.0
213,Executive Suite,8,Low-quality food,2.0
214,Executive Suite,8,Noisy neighbors,4.0
215,Executive Suite,8,"Rodents, roaches, & other unwanted guests",3.0
216,Executive Suite,8,Slow Wi-Fi,1.0
217,Executive Suite,8,Temperature of their room,2.0
218,Executive Suite,8,Issues with staff,1.0
219,Executive Suite,8,No hot water,4.0
220,Executive Suite,9,Bad smells,2.0
221,Executive Suite,9,Dirty rooms,1.0
222,Executive Suite,9,Doesn’t match the website/brochure,1.0
223,Executive Suite,9,Faulty electronics,1.0
224,Executive Suite,9,Low-quality food,1.0
225,Executive Suite,9,Noisy neighbors,3.0
226,Executive Suite,9,"Rodents, roaches, & other unwanted guests",0.0
227,Executive Suite,9,Slow Wi-Fi,4.0
228,Executive Suite,9,Temperature of their room,2.0
229,Executive Suite,9,Issues with staff,4.0
230,Executive Suite,9,No hot water,0.0
231,Executive Suite,10,Bad smells,2.0
232,Executive Suite,10,Dirty rooms,2.0
233,Executive Suite,10,Doesn’t match the website/brochure,4.0
234,Executive Suite,10,Faulty electronics,4.0
235,Executive Suite,10,Low-quality food,4.0
236,Executive Suite,10,Noisy neighbors,4.0
237,Executive Suite,10,"Rodents, roaches, & other unwanted guests",3.0
238,Executive Suite,10,Slow Wi-Fi,3.0
239,Executive Suite,10,Temperature of their room,2.0
240,Executive Suite,10,Issues with staff,2.0
241,Executive Suite,10,No hot water,6.0
242,Executive Suite,11,Bad smells,1.0
243,Executive Suite,11,Dirty rooms,2.0
244,Executive Suite,11,Doesn’t match the website/brochure,1.0
245,Executive Suite,11,Faulty electronics,1.0
246,Executive Suite,11,Low-quality food,2.0
247,Executive Suite,11,Noisy neighbors,5.0
248,Executive Suite,11,"Rodents, roaches, & other unwanted guests",0.0
249,Executive Suite,11,Slow Wi-Fi,3.0
250,Executive Suite,11,Temperature of their room,1.0
251,Executive Suite,11,Issues with staff,3.0
252,Executive Suite,11,No hot water,1.0
253,Executive Suite,12,Bad smells,1.0
254,Executive Suite,12,Dirty rooms,2.0
255,Executive Suite,12,Doesn’t match the website/brochure,3.0
256,Executive Suite,12,Faulty electronics,6.0
257,Executive Suite,12,Low-quality food,3.0
258,Executive Suite,12,Noisy neighbors,2.0
259,Executive Suite,12,"Rodents, roaches, & other unwanted guests",3.0
260,Executive Suite,12,Slow Wi-Fi,1.0
261,Executive Suite,12,Temperature of their room,1.0
262,Executive Suite,12,Issues with staff,4.0
263,Executive Suite,12,No hot water,4.0
264,King Suite,1,Bad smells,11.0
265,King Suite,1,Dirty rooms,5.0
266,King Suite,1,Doesn’t match the website/brochure,5.0
267,King Suite,1,Faulty electronics,14.0
268,King Suite,1,Low-quality food,9.0
269,King Suite,1,Noisy neighbors,17.0
270,King Suite,1,"Rodents, roaches, & other unwanted guests",9.0
271,King Suite,1,Slow Wi-Fi,6.0
272,King Suite,1,Temperature of their room,4.0
273,King Suite,1,Issues with staff,4.0
274,King Suite,1,No hot water,11.0
275,King Suite,2,Bad smells,8.0
276,King Suite,2,Dirty rooms,6.0
277,King Suite,2,Doesn’t match the website/brochure,2.0
278,King Suite,2,Faulty electronics,7.0
279,King Suite,2,Low-quality food,2.0
280,King Suite,2,Noisy neighbors,13.0
281,King Suite,2,"Rodents, roaches, & other unwanted guests",4.0
282,King Suite,2,Slow Wi-Fi,5.0
283,King Suite,2,Temperature of their room,2.0
284,King Suite,2,Issues with staff,4.0
285,King Suite,2,No hot water,9.0
286,King Suite,3,Bad smells,2.0
287,King Suite,3,Dirty rooms,0.0
288,King Suite,3,Doesn’t match the website/brochure,3.0
289,King Suite,3,Faulty electronics,5.0
290,King Suite,3,Low-quality food,2.0
291,King Suite,3,Noisy neighbors,14.0
292,King Suite,3,"Rodents, roaches, & other unwanted guests",4.0
293,King Suite,3,Slow Wi-Fi,5.0
294,King Suite,3,Temperature of their room,4.0
295,King Suite,3,Issues with staff,0.0
296,King Suite,3,No hot water,3.0
297,King Suite,4,Bad smells,3.0
298,King Suite,4,Dirty rooms,2.0
299,King Suite,4,Doesn’t match the website/brochure,2.0
300,King Suite,4,Faulty electronics,3.0
301,King Suite,4,Low-quality food,1.0
302,King Suite,4,Noisy neighbors,8.0
303,King Suite,4,"Rodents, roaches, & other unwanted guests",1.0
304,King Suite,4,Slow Wi-Fi,0.0
305,King Suite,4,Temperature of their room,2.0
306,King Suite,4,Issues with staff,3.0
307,King Suite,4,No hot water,3.0
308,King Suite,5,Bad smells,5.0
309,King Suite,5,Dirty rooms,2.0
310,King Suite,5,Doesn’t match the website/brochure,1.0
311,King Suite,5,Faulty electronics,1.0
312,King Suite,5,Low-quality food,1.0
313,King Suite,5,Noisy neighbors,3.0
314,King Suite,5,"Rodents, roaches, & other unwanted guests",1.0
315,King Suite,5,Slow Wi-Fi,2.0
316,King Suite,5,Temperature of their room,1.0
317,King Suite,5,Issues with staff,1.0
318,King Suite,5,No hot water,1.0
319,King Suite,6,Bad smells,2.0
320,King Suite,6,Dirty rooms,2.0
321,King Suite,6,Doesn’t match the website/brochure,1.0
322,King Suite,6,Faulty electronics,0.0
323,King Suite,6,Low-quality food,0.0
324,King Suite,6,Noisy neighbors,3.0
325,King Suite,6,"Rodents, roaches, & other unwanted guests",1.0
326,King Suite,6,Slow Wi-Fi,1.0
327,King Suite,6,Temperature of their room,2.0
328,King Suite,6,Issues with staff,0.0
329,King Suite,6,No hot water,0.0
330,King Suite,7,Bad smells,5.0
331,King Suite,7,Dirty rooms,0.0
332,King Suite,7,Doesn’t match the website/brochure,1.0
333,King Suite,7,Faulty electronics,3.0
334,King Suite,7,Low-quality food,2.0
335,King Suite,7,Noisy neighbors,6.0
336,King Suite,7,"Rodents, roaches, & other unwanted guests",4.0
337,King Suite,7,Slow Wi-Fi,1.0
338,King Suite,7,Temperature of their room,56.0
339,King Suite,7,Issues with staff,4.0
340,King Suite,7,No hot water,2.0
341,King Suite,8,Bad smells,2.0
342,King Suite,8,Dirty rooms,1.0
343,King Suite,8,Doesn’t match the website/brochure,1.0
344,King Suite,8,Faulty electronics,0.0
345,King Suite,8,Low-quality food,2.0
346,King Suite,8,Noisy neighbors,8.0
347,King Suite,8,"Rodents, roaches, & other unwanted guests",3.0
348,King Suite,8,Slow Wi-Fi,3.0
349,King Suite,8,Temperature of their room,71.0
350,King Suite,8,Issues with staff,0.0
351,King Suite,8,No hot water,2.0
352,King Suite,9,Bad smells,5.0
353,King Suite,9,Dirty rooms,0.0
354,King Suite,9,Doesn’t match the website/brochure,4.0
355,King Suite,9,Faulty electronics,1.0
356,King Suite,9,Low-quality food,2.0
357,King Suite,9,Noisy neighbors,8.0
358,King Suite,9,"Rodents, roaches, & other unwanted guests",3.0
359,King Suite,9,Slow Wi-Fi,8.0
360,King Suite,9,Temperature of their room,97.0
361,King Suite,9,Issues with staff,1.0
362,King Suite,9,No hot water,0.0
363,King Suite,10,Bad smells,0.0
364,King Suite,10,Dirty rooms,1.0
365,King Suite,10,Doesn’t match the website/brochure,1.0
366,King Suite,10,Faulty electronics,2.0
367,King Suite,10,Low-quality food,1.0
368,King Suite,10,Noisy neighbors,3.0
369,King Suite,10,"Rodents, roaches, & other unwanted guests",1.0
370,King Suite,10,Slow Wi-Fi,5.0
371,King Suite,10,Temperature of their room,50.0
372,King Suite,10,Issues with staff,1.0
373,King Suite,10,No hot water,2.0
374,King Suite,11,Bad smells,3.0
375,King Suite,11,Dirty rooms,1.0
376,King Suite,11,Doesn’t match the website/brochure,2.0
377,King Suite,11,Faulty electronics,2.0
378,King Suite,11,Low-quality food,0.0
379,King Suite,11,Noisy neighbors,5.0
380,King Suite,11,"Rodents, roaches, & other unwanted guests",0.0
381,King Suite,11,Slow Wi-Fi,2.0
382,King Suite,11,Temperature of their room,52.0
383,King Suite,11,Issues with staff,0.0
384,King Suite,11,No hot water,1.0
385,King Suite,12,Bad smells,1.0
386,King Suite,12,Dirty rooms,0.0
387,King Suite,12,Doesn’t match the website/brochure,2.0
388,King Suite,12,Faulty electronics,4.0
389,King Suite,12,Low-quality food,0.0
390,King Suite,12,Noisy neighbors,5.0
391,King Suite,12,"Rodents, roaches, & other unwanted guests",3.0
392,King Suite,12,Slow Wi-Fi,5.0
393,King Suite,12,Temperature of their room,54.0
394,King Suite,12,Issues with staff,2.0
395,King Suite,12,No hot water,2.0
396,One-Bedroom Club Room,1,Bad smells,1.0
397,One-Bedroom Club Room,1,Dirty rooms,1.0
398,One-Bedroom Club Room,1,Doesn’t match the website/brochure,1.0
399,One-Bedroom Club Room,1,Faulty electronics,2.0
400,One-Bedroom Club Room,1,Low-quality food,6.0
401,One-Bedroom Club Room,1,Noisy neighbors,0.0
402,One-Bedroom Club Room,1,"Rodents, roaches, & other unwanted guests",2.0
403,One-Bedroom Club Room,1,Slow Wi-Fi,0.0
404,One-Bedroom Club Room,1,Temperature of their room,0.0
405,One-Bedroom Club Room,1,Issues with staff,4.0
406,One-Bedroom Club Room,1,No hot water,0.0
407,One-Bedroom Club Room,2,Bad smells,0.0
408,One-Bedroom Club Room,2,Dirty rooms,1.0
409,One-Bedroom Club Room,2,Doesn’t match the website/brochure,5.0
410,One-Bedroom Club Room,2,Faulty electronics,1.0
411,One-Bedroom Club Room,2,Low-quality food,3.0
412,One-Bedroom Club Room,2,Noisy neighbors,1.0
413,One-Bedroom Club Room,2,"Rodents, roaches, & other unwanted guests",0.0
414,One-Bedroom Club Room,2,Slow Wi-Fi,1.0
415,One-Bedroom Club Room,2,Temperature of their room,0.0
416,One-Bedroom Club Room,2,Issues with staff,2.0
417,One-Bedroom Club Room,2,No hot water,2.0
418,One-Bedroom Club Room,3,Bad smells,0.0
419,One-Bedroom Club Room,3,Dirty rooms,0.0
420,One-Bedroom Club Room,3,Doesn’t match the website/brochure,0.0
421,One-Bedroom Club Room,3,Faulty electronics,3.0
422,One-Bedroom Club Room,3,Low-quality food,3.0
423,One-Bedroom Club Room,3,Noisy neighbors,0.0
424,One-Bedroom Club Room,3,"Rodents, roaches, & other unwanted guests",0.0

In [102]:
ts.to_excel("concern ts.xlsx",index=False)